### ISSUE TITLE
[QUESTION] why is source-map-support required?

### ISSUE THREAD

**Issue by leemhenson** [dynamoose/dynamoose#1019]
### Summary:

`source-map-support` is listed as a `dependency` and is loaded in `lib/index`. I want to use dynamoose but don't want to have that loaded as it [interferes with Sentry's source map features](https://docs.sentry.io/platforms/node/sourcemaps/). Is there a reason why it's required like this? It could be loaded via other means so users don't have to take this dependency too.

Thanks!

**Comment by fishcharlie** [comment]
Without that dependency any errors will have references to the JS compiled files as opposed to the source TS files. We need that dependency so that when users post their stack traces in bug reports we can reference the code the error is coming from.

**Comment by leemhenson** [comment]
Sure, I understand what source-map-support is used for and that it's certainly useful from a library author's perspective. Though, this logic would suggest that every package in npm should have it as a `dependency` and load it directly, but that's not the case. It appears to me that it should be an application-level concern to load this, as the [options](https://github.com/evanw/node-source-map-support#options) it takes will vary depending on the context in which it is used. That's not possible when you load it directly in a library like this. Perhaps you could amend your issue template to make having source-mapped stacktraces a requirement, which would allow you to remove this dependency in the code and package.json?

**Comment by fishcharlie** [comment]
@leemhenson 

> this logic would suggest that every package in npm should have it as a dependency and load it directly

I disagree. A lot of packages only rely on JS and therefore don't require source map support at all. With JS packages, it requires 0 additional effort. You copy the stack trace, and you are good to go. No 3rd party dependency. No extra work from the user. Just copy and go.

The goal is to provide a good balance between that, and requiring users to do a bunch of work to get things working.

> as the options it takes will vary depending on the context in which it is used

How so? When would you ever need to load source maps from a different location than the file system? When would the environment ever be something other than node (Dynamoose only works on Node, not browser)? When would you need to support inline source maps? None of those things apply to Dynamoose.

> Perhaps you could amend your issue template to make having source-mapped stacktraces a requirement

In an **ideal** world, yes this would happen. However, it's a struggle to get users to fill out the issue template in the first place. Adding more steps and complexity, just adds to my work load and harms the project.

The **best** solution that is achievable would to be to use GitHub Actions to build a bot that triggers on every comment and looks to see if a stack trace is included in that comment. If it is, it'll download or build the stack trace directly from the version mentioned in the issue template. Then from there it'll take the stack trace and source map files, and edit the comment to use the outputted stack trace.

Still a few problems and questions with that solution. But it would make the process more seamless while removing a dependency.

All of that being said. I do understand how this can be a roadblock. But, my point is that it's an extremely rare instance, and I'm not sure adding more workload to the issue template will be valuable. In an ideal world as well, other packages or systems shouldn't interfere with this.

---

One more note. The solution for this was after discussions in the TypeScript Discord channels. So it was inspired and heavily influenced by other developers.

I'm all for hearing out other solutions and coming up with a better plan here, but I have my doubts if adding more workload for users will actually be a good thing. It's difficult enough to get users to include the error or stack traces in their issues.

**Comment by leemhenson** [comment]
I can understand your perspective. I suppose one other approach might be to have a "diagnostic" build (includes source-map-support) and a production build (doesn't), but I don't think that's an acceptable solution either. My preference is that libraries shouldn't be doing this sort of environment-modifying side-effect so I'll either just maintain a fork that removes it or go back to `DocumentClient`.

Thanks for your time anyway.

**Comment by martin-oa** [comment]
@fishcharlie 

Hello, I traced back some sourcemap problems we were having in jest directly to this. When running our jest tests we don't get correct line numbers, but if I simply comment out the line `require("source-map-support/register");` in `node_modules/dynamoose/dist/index.js` it gives proper line numbers, and uncommenting it out again makes it fail again. It seems that source-map-support is imported by jest and modifies the global Error object, so when dynamoose imports it as well, it overwrites jest's support for source maps.

Could the import be changed so that it's conditional on Error.prepareStackTrace being undefined? This way if the user has already set up source-map-support it won't overwrite it, but js users or anyone else who did not import it themselves will still get the correct line numbers in their error messages.

This code would do the trick:

```ts
import * as sourceMapSupport from "source-map-support";

if (!Error.prepareStackTrace) {
  // Register source map support only if someone else hasn't already:
  sourceMapSupport.install();
}
```

Thanks for your time.

**Comment by fishcharlie** [comment]
@martin-oa What version of Dynamoose are you running?

**Comment by martin-oa** [comment]
2.8.2

**Comment by martin-oa** [comment]
@fishcharlie 

Oh I see there's a separate branch for version 3. I thought the main branch was the most recent one, I should have looked more carefully. Sorry about that.

Now I did a grep in the v3 branch of dynamoose, and it doesn't import source-map-support anymore. I've also now tested by pointing dynamoose to v3 in the package.json, and it seems this issue is gone in v3. We can't immediately switch to v3 because of the breaking changes, but eventually that will be the solution. Still, if you ever do another release in the 2.x series, the change I proposed would be nice.

Thank you!

**Comment by fishcharlie** [comment]
@martin-oa Yes. So v3 is still in alpha. But has a change where we remove the source-map-support dependency and replace it with a system based on GitHub Issues where it will take a stack trace that hasn't been parsed using the source map, and run it through the system to generate the source map based stack trace and comment that. This also fixes a major performance issue related to source-map-support in Dynamoose.

If you would like to put up a PR for this, I think we might be able to get it into v2. I'm not sure I'm going to have the bandwidth to put up a PR into v2 tho.

Additionally, it's very likely that v3 will be promoted to the main branch after it goes into beta (which I think **might** be soon). So just for sake of it being easy, we might need to do this soon (if we are going to do it at all).
