### ISSUE TITLE
[QUESTION] Any ETA on a new release?

### ISSUE THREAD

**Issue by lmanerich** [dynamoose/dynamoose#1032]
### Summary:
Any ETA on a new release will be dropped?
There is a least 3 issues that I detected, but, looking at the master code, it is fixed.

**Comment by fishcharlie** [comment]
No ETA at this time. I need to find time to review most/all of the open PRs and once those get merged I can work on getting a release out.

Feel free to help review and test the PRs as well as testing the master branch and providing feedback if it works or has problems.

**Comment by fishcharlie** [comment]
@lmanerich Biggest hold up for a new release currently is getting more reviews on #918. Ideally I'd like to have @sreeparnabanerjee53 and/or @thebrokenbar review it to make sure it solves the bug they ran into.

If I can find time next weekend, new release should happen next weekend at the latest even with no reviews on that PR. Otherwise it could happen earlier.

**Comment by fishcharlie** [comment]
@lmanerich v2.4.0 has been submitted to NPM! Be sure to leave feedback.
