### ISSUE TITLE
[BUG] dynamoose nested default value is not correctly set

### ISSUE THREAD

**Issue by shihminlee** [dynamoose/dynamoose#1045]
### Summary:

dynamoose default value is not correctly set when you do `model.create` on nested array. If you have default value `[]` on the array and the array element then when you do `model.create` it would not create an empty array.

#### Schema
```
const schema = {
    "uid": String,
    runs: {
        type: Array,
        schema: [{
          type: Object,
          schema: RunSchema,
        }],
        default: [],
      },
}

const RunSchema = {
  idx: {
    type: Number,
    default: 0
  },
};
```

#### Model
n/a

#### General
```
const SomeModel = dynamoose.model("...", schema);

SomeModel.create({"uid": "xxx"}, {return: 'response'})
  .then(inventory => {
    console.log(inventory);
    SomeModel.get(id, (err, inventory) => {
      console.log(inventory);
      res.send(inventory)
    })
  })
```

### Current output and behavior (including stack trace):
```
 { uid: 'aaaa', runs: [ { idx: 0 } ] }
```

### Expected output and behavior:
```
 { uid: 'aaaa', runs: [] }
```

### Environment:

Operating System: MacOS / ubuntu
Operating System Version: 
Node.js version (`node -v`): v12.13.1
NPM version: (`npm -v`): 6.12.1
Dynamoose version: 2.4.0

### Other information (if applicable):
n/a

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [x] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [x] I have tested the code provided and am confident it doesn't work as intended
- [x] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
@shihminlee Thanks for reporting this! Kinda concerned this is a breaking change. Tho at the same time it definitely doesn't seem like expected behavior, so probably not.

Not really sure how difficult this is gonna be to fix tho. Will try to look into this more when I have time. Thanks for the report!

**Comment by shihminlee** [comment]
@fishcharlie I remember looking into the code before and my impression is it read all the nested default value into a map and then later serializes the object using that map. Something like this 


```
{
  runs: [], <-- default value of runs
  runs.0.idx: 123 <--- default value of idx
}
```

And then the nested value gets stuck in there.

**Comment by fishcharlie** [comment]
I think this might be related to #900.

**Comment by fishcharlie** [comment]
After looking at this more, this is the expected behavior. There is no reason for Dynamoose to assume that we should create an object within your array as part of the default action. One option would be to pass in `runs: [{}]` into your creation object. Then the default value should be applied.

But Dynamoose shouldn't create objects for you, and there is no telling how many objects you want us to create inside the array. It is very hard for Dynamoose to determine what the intended behavior here is, so it's best that Dynamoose do nothing in this case.
