### ISSUE TITLE
Nested schema model wont be created (on db record)

### ISSUE THREAD

**Issue by softmarshmallow** [dynamoose/dynamoose#1048]
``` ts

        const someChild = <NestedLayerRecord>{
            id: "testing id",
            nodeId: "",
            key: undefined,
            index: 0,
            name: "",
            sdkVersion: sdkVer,
            node: {
                text: "hi~"
            },
            type: StorableLayerType.vanilla,
            layers: undefined,
            componentId: undefined,
            width: 0,
            height: 0,
        }


        const layer = <NestedLayerRecord>{
            id: "testing id",
            nodeId: "",
            key: undefined,
            index: 0,
            name: "",
            sdkVersion: sdkVer,
            node: {},
            type: StorableLayerType.vanilla,
            layers: [someChild,],
            componentId: undefined,
            width: 0,
            height: 0,
        }

        console.log('layer', layer)


        const scene = new Scene({
            id: "test",
            projectId: "demo",
            fileId: "test",
            nodeId: "test",
            sdkVersion: sdkVer,
            designPlatform: DesignPlatform.figma,
            cachedPreview: "https://example.com/dog.png",
            sceneType: StorableSceneType.screen,
            route: "/home",
            path: "/home",
            name: "home",
            description: "home screen",
            tags: ["1", "2"],
            alias: "home",
            variant: "default",
            layers: [layer],
            width: 100,
            height: 100,
        });

        const saved = await scene.save()
        console.log('screen registered', saved)
```

Schema

``` ts


export const NestedLayer = new dynamoose.Schema({
    nodeId: String,
    key: String,
    index: Number,
    name: String,
    sdkVersion: String,
    node: Object,
    type: {
        "type": String,
        "enum": ["INSTANCE", "GROUP", "VANILLA"]
    },
    layers: {
        type: Array,
        schema: {
            nodeId: String
        }//dynamoose.THIS as any
    },
    componentId: String,
    width: Number,
    height: Number,
})

export const Scene = dynamoose.model(TABLE, {
    id: String,
    projectId: String,
    fileId: String,
    nodeId: String,
    sdkVersion: String,
    //DesignPlatformType
    designPlatform: {
        "type": String,
        "enum": ["com.figma.Desktop", "com.bohemiancoding.sketch3", "xyz.bridged.bridged"]
    },
    cachedPreview: String,
    // SceneType
    sceneType: {
        "type": String,
        "enum": ["SCREEN", "COMPONENT", "DOCS"]
    },
    route: String,
    path: String,
    name: String,
    description: String,
    tags: {
        "type": Set,
        "schema": [String]
    },
    alias: String,
    variant: String,
    layers: {
        type: Array,
        schema: [NestedLayer as any]
    },
    width: Number,
    height: Number
});

```

logs
```
layer {
  id: 'testing id',
  nodeId: '',
  key: undefined,
  index: 0,
  name: '',
  sdkVersion: 'v2020.0',
  node: {},
  type: 'VANILLA',
  layers: [
    {
      id: 'testing id',
      nodeId: '',
      key: undefined,
      index: 0,
      name: '',
      sdkVersion: 'v2020.0',
      node: [Object],
      type: 'VANILLA',
      layers: undefined,
      componentId: undefined,
      width: 0,
      height: 0
    }
  ],
  componentId: undefined,
  width: 0,
  height: 0
}
screen registered Document {
  id: 'test',
  projectId: 'demo',
  fileId: 'test',
  nodeId: 'test',
  sdkVersion: 'v2020.0',
  designPlatform: 'com.figma.Desktop',
  cachedPreview: 'https://example.com/dog.png',
  sceneType: 'SCREEN',
  route: '/home',
  path: '/home',
  name: 'home',
  description: 'home screen',
  tags: [ '1', '2' ],
  alias: 'home',
  variant: 'default',
  layers: [
    {
      nodeId: '',
      key: undefined,
      index: 0,
      name: '',
      sdkVersion: 'v2020.0',
      node: {},
      type: 'VANILLA',
      layers: [],  // <-------------------------------- HERE IT'S MEPTY?
      componentId: undefined,
      width: 0,
      height: 0
    }
  ],
  width: 100,
  height: 100
}
```

**Comment by softmarshmallow** [comment]
found a way (A BAD WAY) to get this done.


``` ts

export const NestedLayer = new dynamoose.Schema({
    nodeId: String,
    key: String,
    index: Number,
    name: String,
    sdkVersion: String,
    node: Object,
    type: {
        type: String,
        enum: ["INSTANCE", "GROUP", "VANILLA"]
    },
    layers: {
        type: {
            value: Array,
            settings: {
                model: dynamoose.THIS as any
            }
        },
    },
    componentId: String,
    width: Number,
    height: Number,
}, {
    saveUnknown: true,
})


export const SceneScheam = new dynamoose.Schema({
    id: String,
    projectId: String,
    fileId: String,
    nodeId: String,
    sdkVersion: String,
    //DesignPlatformType
    designPlatform: {
        type: String,
        enum: ["com.figma.Desktop", "com.bohemiancoding.sketch3", "xyz.bridged.bridged"]
    },
    cachedPreview: String,
    // SceneType
    sceneType: {
        type: String,
        enum: ["SCREEN", "COMPONENT", "DOCS"]
    },
    route: String,
    path: String,
    name: String,
    description: String,
    tags: {
        type: Set,
        schema: [String]
    },
    alias: String,
    variant: String,
    layers: {
        type: Array,
        schema: [NestedLayer as any]
    },
    width: Number,
    height: Number,
    background: String
}, {
    // https://github.com/dynamoose/dynamoose/pull/1050
    saveUnknown: true
})

```

**Comment by softmarshmallow** [comment]
Leaving this issue open, since it's typescript mismatch related issue. (in a way)

**Comment by fishcharlie** [comment]
Closing due to not following the issue template and not using MCVE examples.

**Comment by softmarshmallow** [comment]
Whoa. where did that come from

**Comment by fishcharlie** [comment]
@softmarshmallow At the top of the issue template it's **very clear**: `<!-- Not filling out ALL of the relevant fields in this issue will cause your issue to be closed -->`. This is not a new policy, and isn't something that I just started. It's not like it came out randomly.

That is the short version for your `where did that come from` comment. Below I go into a lot more detail about **why** that policy exists and my perspective as a Dynamoose maintainer when I see an issue like this.

---

I know this rule might seem overly strict. But part of running an open source project is having good organization. We currently have 50 open issues. That is a **lot** to manage. And I have limited time to spend on this project. So because I have limited time, I have to ask myself, should I prioritize the issues that make my job easier (primarily by following the template and following the contributing guidelines) OR do I prioritize the issues that make my job harder by not following the guidelines and require me to dig through a ton of code that doesn't follow the MCVE pattern? I choose to prioritize the issues that follow the template and contributing guidelines to make my job easier.

I'm well aware that it's more difficult and takes more time to write a good issue that follows the guidelines. But if you aren't willing to spend the time to follow the guidelines, why should I spend time on your issue? Help me help you by writing good issues.

I'll also point out that in your issue #1052. If you had followed the issue template you would have seen a checkbox for `I have read through the Dynamoose documentation before posting this issue`. That might have helped save both of us time since I linked you right to the documentation that answered your question. OR it would have shown that you at least put in effort into looking at the documentation. Then the discussion could have been "How can we make this part of the documentation easier to find?" as opposed to just a link to the documentation.

The issue template is also designed to help you slow down and make sure the issue is actually occurring and isn't an oversight or problem on your end. I think I saw an issue from you that you said you resolved shortly after posting it. The issue template is designed to really help users think about their issue and reproduce it in an example project to pin point the issue and slow down.

---

Now in regards to this issue specifically. Here are the first things that stand out to me.

1. `const layer = <NestedLayerRecord>{` makes no sense to me. Maybe that is my fault, but I've never seen that syntax before. What does `<NestedLayerRecord>` mean? Is that a TypeScript feature? Not a big deal, I can do more research about this **IF** it was the only problem.
2. In `layer` and `someChild` you have like over 10 properties in each object. Is that necessary for me to see? Does the problem only occur when you have that many properties? If so, you need to explain that and make it clear. If not, you need to reduce the code to make it easier for me to debug and so I don't have to dig through massive objects to find the problem.
3. `console.log('layer', layer)` in this case doesn't help me at all. The **only** reason to put this is if the output is strange or unexpected. And it should include the output in this case. But right now, that just adds unnecessary code and is one more thing I have to look through to find the problem.
4. `found a way (A BAD WAY) to get this done` gives 0 detail about why you believe it's a bad way. It's also unclear what exactly changed. I have to dig through your TONS of code to find what changed. There is no general description about what you did to fix it. What line(s) of code did you add or remove? Do I really need to see all your code again?
5. Lots of other little information that isn't included. Did you look through other issues and find any thing that might be relevant? What version of Dynamoose are you running (could it be an outdated version issue)? What else have you tried to fix this (you gave a solution after posting your issue)?
6. Is this specific to TypeScript? Or does it occur in vanilla JS as well?
7. Did you read through the `dynamoose.THIS` documentation? It is only used for populating documents, and isn't related to referencing the own schema recursively within a single document. Which makes me think you are using it wrong. There is a question in the issue template about reading the documentation. Which applies here. It helps me not waste time asking if you read through the documentation.

I could go on and on. But there is a **lot** here. I liked your `// <- HERE IT'S MEPTY?` comment. That helps a lot. But it took me a while to find it because I had to dig through the rest of your code that isn't even related to the issue.

There is a chance based on that, that I could spend time finding the issue in Dynamoose. **BUT** it will require a lot of work digging through all your code that doesn't matter. And everything I mentioned above, will delay my effort to figure it out and require me to spend more time. Which gets back to prioritizing issues.

---

I hope this gives perspective into my role as a project maintainer. I know it's frustrating and requires more work for you. However I know for a fact that Dynamoose is not the only project who has similar rules. And I do my best to set a good middle ground. A lot of other projects don't even allow questions on their GitHub Issue tracker and redirect users to Stack Overflow or other channels. I try to be as flexible and open as possible, while still ensuring I'm prioritizing things in a good way to the benefit of this project.

Apologizes that your issue got closed. And I hope this answer helps explain the reasoning behind it.
