### ISSUE TITLE
[BUG] TypeError: key.split is not a function

### ISSUE THREAD

**Issue by softmarshmallow** [dynamoose/dynamoose#1068]
### Summary:
TypeError: key.split is not a function on typescript api usage

#### Schema
```


const TABLE = process.env.DYNAMODB_TABLE


export const NestedLayer = new dynamoose.Schema({
    nodeId: String,
    key: String,
    index: Number,
    name: String,
    sdkVersion: String,
    node: Object,
    type: {
        type: String,
        enum: ["INSTANCE", "GROUP", "VANILLA"]
    },
    layers: {
        type: {
            value: Array,
            settings: {
                model: dynamoose.THIS as any
            }
        },
    },
    componentId: String,
    width: Number,
    height: Number,
}, {
    saveUnknown: true,
})


export const SceneSchema = new dynamoose.Schema({
    id: String,
    projectId: String,
    fileId: String,
    nodeId: String,
    sdkVersion: String,
    //DesignPlatformType
    designPlatform: {
        type: String,
        enum: ["com.figma.Desktop", "com.bohemiancoding.sketch3", "xyz.bridged.bridged"]
    },
    cachedPreview: String,
    // SceneType
    sceneType: {
        type: String,
        enum: ["SCREEN", "COMPONENT", "DOCS"]
    },
    route: String,
    name: String,
    description: String,
    tags: {
        type: Set,
        schema: [String]
    },
    alias: String,
    variant: String,
    layers: {
        type: Array,
        schema: [NestedLayer as any]
    },
    width: Number,
    height: Number,
    background: String
}, {
    // https://github.com/dynamoose/dynamoose/pull/1050
    saveUnknown: true
})

```

#### Model
```
export const Scene = dynamoose.model(TABLE, SceneSchema, {
    create: false
});

```

#### General
```
async registerScreen(request: SceneRegisterRequest) {

        // convert storable layer from request to nested layer record.
        const nestedLayers: NestedLayerRecord[] = request.layers.map((l: StorableLayer) => {
            const nestedLayer = convertStorableLayerToNestedLayer(l)
            return nestedLayer
        })


        const id = nanoid()
        const scene = new Scene({
            id: id,
            projectId: request.projectId,
            fileId: request.fileId,
            nodeId: request.nodeId,
            sdkVersion: sdkVer,
            designPlatform: DesignPlatform.figma,
            cachedPreview: request.preview,
            sceneType: request.sceneType,
            route: request.route,
            name: request.name,
            description: request.description,
            tags: request.tags,
            alias: request.alias,
            variant: request.variant,
            layers: nestedLayers,
            width: request.width,
            height: request.height,
        });

        const saved = await scene.save()

        return saved
    }
```

### Current output and behavior (including stack trace):

TypeError: key.split is not a function
    at /Users//Documents/GitHub/services/node_modules/dynamoose/lib/utils/dynamoose/wildcard_allowed_check.ts:4:25
    at Array.find (<anonymous>)
    at Object.module.exports [as wildcard_allowed_check] (/Users//Documents/GitHub/services/node_modules/dynamoose/lib/utils/dynamoose/wildcard_allowed_check.ts:3:30)
    at checkTypeFunction (/Users//Documents/GitHub/services/node_modules/dynamoose/lib/Document.ts:329:50)
    at Array.map (<anonymous>)
    at Function.<anonymous> (/Users//Documents/GitHub/services/node_modules/dynamoose/lib/Document.ts:334:111)
    at Generator.next (<anonymous>)
    at fulfilled (/Users//Documents/GitHub/services/node_modules/dynamoose/dist/Document.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

### Environment:

Operating System: OSX
Operating System Version: 11.0
Node.js version (`node -v`): v12.18.0
Yarn version: (`yarn -v`): 1.22.4
Dynamoose version: 2.4.0

### Other information (if applicable):

For some unknown reason, maintainer closed the previous issue for no reason.
https://github.com/dynamoose/dynamoose/issues/1049

### Other:
- [V ] I have read through the Dynamoose documentation before posting this issue
- [V ] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [V ] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [V ] I have tested the code provided and am confident it doesn't work as intended
- [V ] I have filled out all fields above
- [V ] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
@softmarshmallow 

> For some unknown reason

https://github.com/dynamoose/dynamoose/issues/1049#issuecomment-734638652

That is an unknown reason? Umm, no. I was very clear about my reason. Maybe you just didn't read it.

You still didn't follow the guidelines. This issue still doesn't have an MCVE. We've been over this over and over. What is `request` equal to? What is `nanoid()` equal to? I'm **very** confident you could have used less code, it's not minimal at all. Also if you are running the latest version of Dynamoose that would be 2.4.1 not 2.4.0. List goes on and on.

I'm not sure how you expect me to be able to reproduce this. If I ran this code just as it is, it'd give so many undefined variable errors. What makes you think I'll be successful in running your code here?

I've asked you questions. I've given you reasons. I've explained the guidelines. There is nothing more I can do.

We've been over this so many times.

If you don't understand what I've said, please ask for clarification. But right now it seems like you are just ignoring what I say and acting like you have 0 respect for me or this projects guidelines.

---

Due to the fact that you have repeatedly not followed the Dynamoose guidelines, please be warned of the following:

In the event you continue to create issues or PRs without following the guidelines the following might happen:

- Issues or PRs you create will be subject to being closed immediately with no explanation
- There might be other action taken against you such as (but not limited to) being blocked from creating issues or PRs on this repo

I know this is harsh. But I've been extremely clear. It's unfair for you to keep wasting my time when you are putting in almost no effort into writing your issues.
