### ISSUE TITLE
[BUG] Expected assets to be of type object, instead found type object.

### ISSUE THREAD

**Issue by softmarshmallow** [dynamoose/dynamoose#1072]
### Summary:
Schema field typed to be Object, passed object, but db transaction will be rejected with message
`Expected assets to be of type object, instead found type object.`

#### Schema
``` ts

const VariantAssetSchema = new dynamoose.Schema({
    id: {
        type: String,
        default: () => nanoid()
    },
    projectId: {
        type: String,
        required: true,
    },
    key: {
        type: String,
        required: true,
    },
    name: {
        type: String,
        required: false
    },
    description: {
        type: String,
        required: false
    },
    type: {
        type: String,
        enum: ["URI", "TEXT", "IMAGE", "ICON", "ILLUST", "COLOR", "FILE", "UNKNOWN"],
        required: true
    },
    // TODO change type to string: string map -> {variant: raw-asset-id}
    assets: {
        type: Object,
        default: {},
        required: true
    }
}, {
    saveUnknown: true
})
```

#### Model
``` ts
const TBL_VARIANT_ASSETS = process.env.DYNAMODB_TABLE_VARIANT_ASSETS
export const VariantAssetModel = dynamoose.model(TBL_VARIANT_ASSETS, VariantAssetSchema, {
    create: false
})
```

#### General
``` ts

const obj = new Map()
obj.set('A', 'B')


// Code here
        const record = new VariantAssetModel(<VariantAssetTable>{
/// from here
            id: id,
            key: request.key,
            projectId: projectId,
            name: request.name,
            type: request.type,
            description: request.description,
// to here works fine.

// error-causing line
            assets: obj
        })
        const created = await record.save()

```

### Current output and behavior (including stack trace):

object cannot be assiged to field type Object

```
TypeMismatch: Expected assets to be of type object, instead found type object.
    at checkTypeFunction (/Users//Documents/GitHub/services/node_modules/dynamoose/lib/Document.ts:313:11)
    at Array.map (<anonymous>)
    at Function.Document.objectFromSchema (/Users//Documents/GitHub/services/node_modules/dynamoose/lib/Document.ts:334:111)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Document.toDynamo (/Users//Documents/GitHub/services/node_modules/dynamoose/lib/Document.ts:492:17)
    at async Promise.all (index 0)
    at /Users//Documents/GitHub/services/node_modules/dynamoose/lib/Document.ts:176:5
```

### Expected output and behavior:

to accept object or more helpful error message for debugging

### Environment:

Operating System: MacOS BigSur
Node.js version (`node -v`): 12.18
Dynamoose version: 2.4.1

### Other:
- [ V] I have read through the Dynamoose documentation before posting this issue
- [ V] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [ V] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [ V] I have tested the code provided and am confident it doesn't work as intended
- [ V] I have filled out all fields above
- [ V] I am running the latest version of Dynamoose

**Comment by softmarshmallow** [comment]
DO NOT CLOSE THIS ISSUE WITHOUT VIABLE WORKAROUND

Temporary solution

> unwrap the object , wrap it again.
```
            assets: { ...assetIdMap }
```

**Comment by fishcharlie** [comment]
I can't reproduce this. I ran the following code:

```js
(async () => {
	const dynamoose = require('dynamoose')
	dynamoose.aws.ddb.local();

	const Schema = new dynamoose.Schema({
		"id": String,
		"assets": {
			type: Object,
			default: {},
			required: true
		}
	}, {
		saveUnknown: true
	});

	await dynamoose.aws.ddb().createTable({
		AttributeDefinitions: [
			{
				AttributeName: "id",
				AttributeType: "S"
			},
		 ],
		 KeySchema: [
			{
				AttributeName: "id",
				KeyType: "HASH"
			},
		],
		ProvisionedThroughput: {
			ReadCapacityUnits: 5,
			WriteCapacityUnits: 5
		},
		"TableName": "Model1"
	}).promise();
	const Model = dynamoose.model("Model1", Schema, {
		create: false
	});

	const record = new Model({
	/// from here
		"id": "myid",
	// to here works fine.

	// error-causing line
		"assets": {"a": "b"}
	});
	console.log("Created record variable");
	const created = await record.save();
	console.log("Saved document: ", created);
	const getRecord = await Model.get("myid");
	console.log("Get record: ", getRecord);
})();
```

And my console out put was:

```
charliefish@Charlies-MBP tmp2 % node index.js
Created record variable
Saved document:  Document { id: 'myid', assets: { a: 'b' } }
Get record:  Document { id: 'myid', assets: { a: 'b' } }
```

As you can see, I got no errors. If I can't reproduce this, I can't fix it.

**Comment by softmarshmallow** [comment]
I've updated my comment. passing Map instance will cause this error.

**Comment by fishcharlie** [comment]
@softmarshmallow Got it. I was able to reproduce this.

Few questions for you:

1. What is the use case here? Why do you need to use map instead of object?
2. Why is `{ ...assetIdMap }` considered a temporary solution? That seems like a good solution to me.

The problem here, is I don't know how to fix this. Maps are a lot more flexible in terms of what the key type can be. You could have an array as a key parameter.

In the end, the solution Dynamoose would do is `{ ...assetIdMap }`. BUT that means that any side effects of that action, will be hidden to the developer. Which could create real problems. I'd prefer to force the developer to do that as opposed to Dynamoose, so the developer can be aware of any side effects that come as a result of that.

Maybe a good option would be to improve the error message here? There are reasons why that is tricky from the internal Dynamoose code perspective. It's not quite straight forward as you'd think. But I'd be open to considering that. Maybe change the error to `Expected assets to be of type object, instead of type map.`? Again, I think that might be tricker then it looks to start.

What are your thoughts? After hearing all of that and the potential problems that could cause, do you think attempting to update the error message will be good enough? Or do you have reasons for why having Dynamoose allow it, is the better choice?

**Comment by softmarshmallow** [comment]
A. if you are not planning of changing logic for acceptinh sldo map type, error message must be fixed.
B. map are considered as object anyway. map is typescript way of making typed structure object.
C. other genral orm, utils accepts map as an object, intuitive.

Any other thoughts?

**Comment by fishcharlie** [comment]
@softmarshmallow 

> if you are not planning of changing logic for acceptinh sldo map type, error message must be fixed.

I kinda explained why this isn't as straight forward as it looks. Feel free to create a PR if you want. But for me it's lower priority right now.

> map are considered as object anyway.

So is any instance of a custom class I create. I gave you my thought process behind this behavior. You didn't respond to any of my points I made tho.

> map is typescript way of making typed structure object.

Umm. No? You can use standard (non map) objects in TypeScript...

> other genral orm, utils accepts map as an object, intuitive.

I gave you my reasons for why I'm hesitant about this. Respond to what I said, not what other ORMs do.

---

Due to the fact that you didn't respond to my comment or answer my questions, I'm closing this issue as stale.

If you have a response to what I said, comment and I'll consider reopening.

**Comment by softmarshmallow** [comment]
Just change the error message. it makes no sense. ok?

**Comment by fishcharlie** [comment]
@softmarshmallow You are **more than welcome** to create a PR 😃.

> The others, honestly i'm tired.

Not sure what you expect when creating an issue. When creating an issue here, it's very rarely a "hey fix this for me" thing, and I do it. It's a back and forth discussion to come up with a great resolution. If you are too tired to answer my questions and have a discussion, don't create issues.

There are 42 open issues right now on this repo. I have the right to prioritize my time as I see fit. Do you think I'm not tired too? You **have to work with me and answer my questions** if you want me to prioritize your issues. Otherwise I seriously will consider blocking you from creating issues. I've warned you so many times at this point.

And it's not that I don't agree with you. I agree that error message isn't the most clear. But do you understand what's involved in fixing it? Have you looked at the internal Dynamoose code for how we generate that error message? It has a **lot** of really complex logic that goes into it. I know you think this is easy, it's not. And I've explained that above.

And any solution you come up with, I can almost **guarantee** I could break it and cause Dynamoose to give the same error message you reported, even after you fixed it.
