### ISSUE TITLE
[FEATURE] Option to conform model to schema

### ISSUE THREAD

**Issue by MaximilianSchon** [dynamoose/dynamoose#1106]
### Summary:

When fetching items that do not conform to the schema a validation error is thrown. It would be nice to have an option to just remove the data that does not pass validation correctly instead.
<s>The same thing goes for when saving data. It would be nice to have an option that it removed the fields that are not valid, instead of throwing an exception. </s>

If the data is already stored and is incorrect, it allows us to still access the correct portion of the data. 

As Dynamo is not very nice to update on a large scale, being able to simply update schemas instead of having to write migration code would be very beneficial. 

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this feature has not already been suggested before
- [x] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
@MaximilianSchon Can you please give an example? Are you trying to use the `validate` option?

**Comment by MaximilianSchon** [comment]
> @MaximilianSchon Can you please give an example? Are you trying to use the `validate` option?

Yes. I realise that I was very unspecific in the original post and I had not explored the exact condition enough to be more specific, I'm sorry.

When you have defined a schema, for example you have defined contactOptions to be of the type number, but the value stored in the database is of type boolean, when fetching the values, a TypeMismatch error is thrown. I would like an option for that exception to be caught and simply remove the incorrect data from the fetched document. It would also be nice to have a similar behaviour on saving data, as you would likely not want to save an incorrect type to the database, and you would still want to save the correct data to avoid data loss. 

The schema would look like:

```
new dynamoose.Schema({
    "PK": {
        "type": String,
        "hashKey": true
    },
    "SK": {
        "type": String,
        "rangeKey": true,
    },
    "contactOptions": Number,
})
```

**Comment by fishcharlie** [comment]
@MaximilianSchon 

> for example you have defined contactOptions to be of the type number, but the value stored in the database is of type boolean, when fetching the values, a TypeMismatch error is thrown

Yes. That is the expected result.

> I would like an option for that exception to be caught and simply remove the incorrect data from the fetched document

I'd love to understand why. In what case will `contactOptions` ever be a Boolean instead of a Number? That seems to indicate corrupted data. The entire point of Dynamoose is to take DynamoDB which is inherently a non structured database, and add structure and conformity to it. If that isn't what you are looking for, I question if Dynamoose is the best solution for you.

> It would also be nice to have a similar behaviour on saving data, as you would likely not want to save an incorrect type to the database, and you would still want to save the correct data to avoid data loss

This is fair, however, this behavior as far as I'm aware doesn't exist on Mongoose. I think at some point it'd be nice to add an optional feature to throw an error instead of failing silently, but I do not foresee us providing an option to save data that doesn't conform to the schema. That removes the entire purpose of Dynamoose. If you think we should consider throwing an error in this case, please submit a specific issue for this.

---

If you truly want to work around this, there are two options.

Firstly, you can add multiple types to `contactOptions`. For example you can change it to: `"contactOptions": [Number, Boolean]`. This will allow either a Number or Boolean to be stored as `contactOptions`.

Second, you could use the `saveUnknown` schema setting. This would likely require you to remove `contactOptions` from your schema. The consequence of this is you lose all strictness related to this.

Neither of those options are recommended. You are basically bypassing the entire purpose of Dynamoose. If you don't want schemas at all, why not just use underlying AWS-SDK? It feels like you want some strictness in terms of your data, but don't want to accept the complete strictness of it. Which gets into **extremely** poor programming practices in my opinion.

**Comment by MaximilianSchon** [comment]
@fishcharlie 

It seems the behavior I am after already exists on regular data fields, but not on timestamps as far as saving data. When putting a number into a string, it just does not save this field, but saves the other ones. However, when saving a timestamp as another data type it throws an exception. I expected dynamoose to be consisted in this behavior and thought I could generalize the case, but it seems like it throws an error only when the timestamp is of the wrong type, but it silently swallows the error if another field is of the wrong type. I think for this case, I will simply remove the timestamp option and include these explicitly in the schema, but I do think that they should work just as the regular fields. 

When it comes to fetching the data, I would expect it to work the same as when saving the data. If you have corrupted data, it would silently remove the incorrect fields instead of throwing an error.

For me at least, this behavior being reasonable gets clear when you are using the query function and it throws an exception because one of the queried documents is incorrect. Here the expected behavior should be either to remove the incorrect field - or at the very least, remove the incorrect document, as it would do when saving the data. 

I absolutely love how dynamoose works when it comes to having strict data, but I do not think that the changes I suggest removes that strictness - it still gurantees that the data matches the schema. If the variables that do not match are removed, the data that is being returned from and inserted into the database, should always be correct. Especially if defaults are applied after removing the non-matching fields. 

I do not know the behavior of mongoose, I have only worked with SQL-databases earlier, where I in these scenarios would simply perform a migration to gurantee that the data matches the schema, but mass-updating on NoSQL-databases (at least dynamo) is much harder and more expensive.

**Comment by fishcharlie** [comment]
Closing this issue due to lack of detail and not filling out the issue template.

---

Just for more context @MaximilianSchon, first you didn't provide an example, then you provided an example with `contactOptions`. Now you are talking about timestamps. How are timestamps related to `contactOptions`?

Timestamps are 100% handled by Dynamoose. You shouldn't be setting them at all. If you are, you don't want to be using timestamps and you should be using your own attributes.

You also didn't address a very critical part of my response: `In what case will contactOptions ever be a Boolean instead of a Number?`.

> When it comes to fetching the data, I would expect it to work the same as when saving the data. If you have corrupted data, it would silently remove the incorrect fields instead of throwing an error.

It does. It works exactly the same. In fact the very same function that handles type checking gets called for both saving and retrieving data.

This gets to the point where filling out the issue template is required. If you had filled out the issue template, it would have given a lot more information. For example, are you running an old version of Dynamoose that causes problems here? Are you using some incorrect code that is causing problems?

This also seems much more like a bug than a feature request.

> Also, in combination with calling get on the data before doing any type of validation (type validation and data validation) this would provide a super nice way of performing data migrations. If you had a field in the database that is saved as a boolean - and is supposed to be a number, as you want to increase the number of options the user have, you could simply have the set function check if the value is a boolean, and in this scenario set it to the new corresponding number.

Again. Please explain the use case for this. In what case will you **ever** have an attribute saved as a boolean that is supposed to be a number? This again indicates corrupted data. Having Dynamoose handle this seems like a very bad idea. It indicates that you have much bigger problems to resolve. Dynamoose should not be opinionated in this way.

Now, if you have 2 completely unrelated attributes, then just make a new attribute for that new data.

---

Apologizes for potentially coming off strict, but having a lot of back and forth like this (that isn't related to the best path forward) doesn't benefit the project. Having back and forth is fine when we are debating the best way to implement something. But back and forth related to miscommunications and not being on the same page, just wastes everyones time. I'm totally willing to help users with Dynamoose, however, this isn't my full time job, and there are a lot of users to help. So please respect my time by putting effort into explaining your problem clearly, concisely, and giving me the information necessary to solve it. That is why we have policies about filling out the issue template, and making things clear.

**Comment by MaximilianSchon** [comment]
> Closing this issue due to lack of detail and not filling out the issue template.
> 
> Just for more context @MaximilianSchon, first you didn't provide an example, then you provided an example with `contactOptions`. Now you are talking about timestamps. How are timestamps related to `contactOptions`?
> 

Sorry. I expected them to work internally as all the other fields and hence I treated them as such, so in my mind they were the same. 

> You also didn't address a very critical part of my response: `In what case will contactOptions ever be a Boolean instead of a Number?`.
> 

I was thinking that when the needs change, in the given scenario when contactOptions initially meant "send email notifications" or "don't send email notifications" it would likely be a boolean, but when a third option, "send text notifications" gets added it could change to a number. I thought I added this, but I must have removed it to stay consice. 

> 
> It does. It works exactly the same. In fact the very same function that handles type checking gets called for both saving and retrieving data.
> 
> This gets to the point where filling out the issue template is required. If you had filled out the issue template, it would have given a lot more information. For example, are you running an old version of Dynamoose that causes problems here? Are you using some incorrect code that is causing problems?
> 
> This also seems much more like a bug than a feature request.
> 

I will look into this and see if I can provide a bug report instead. I have read through the documentation but I can't find anything proper on how it is supposed to behave. However, I have never looked into the documentation on mongoose, which might be the issue in this case. 

> Apologizes for potentially coming off strict, but having a lot of back and forth like this (that isn't related to the best path forward) doesn't benefit the project. Having back and forth is fine when we are debating the best way to implement something. But back and forth related to miscommunications and not being on the same page, just wastes everyones time. I'm totally willing to help users with Dynamoose, however, this isn't my full time job, and there are a lot of users to help. So please respect my time by putting effort into explaining your problem clearly, concisely, and giving me the information necessary to solve it. That is why we have policies about filling out the issue template, and making things clear.

I am sorry. If I open another issue I will make sure to fill it in properly. I just was not really sure how much information was needed and I am not very used to working with open source tools - I think I have not grasped entirely what is related to an issue. I tend to treat it more like "I want to solve this problem" than "this is the specific solution I want to use to solve this problem", but in this scenario I had a solution which would work for me, but the central thing for me was still not the solution but the problem. 

I do appreciate your time and I am sorry for not being clearer.
