### ISSUE TITLE
[FEATURE] dynamoose.logger.providers log exception

### ISSUE THREAD

**Issue by arnoldsi-vii** [dynamoose/dynamoose#1111]
### Summary:
I really like using dynamoose for as my provider. 
There is one thing I cannot find and it's central error handling/logging.
dynamoose allows setting custom providers, but it's only triggering log function and never error function, even if I get error such as: 
`ExpressionAttributeNames must not be empty `

It would be great if you can return the error and the request that you made to the error handler so it will be much easier to debug and log.

Thank you

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this feature has not already been suggested before
- [x] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
@arnoldsi-vii This is something we have to do. The concern here is keeping the code DRY. In order to do this we'd have to add logging code to the top of every single function. What happens if we write a new function where we forget to add logging?

I know logging sounds like a simple thing to do, but this project really places a high focus on having things be DRY, reusable, and scalable. Things should just work.

One solution might be to add automated tests to fail if logging isn't added, but again, not confident that is the BEST solution.

Ideally what we'd have is almost like a custom Function Class, and we convert all of our functions to inherit from that class. Then that class would handle all of the logging itself. I'm not sure **exactly** if that is the best option, but the idea is write once, works everywhere. That is what we'd be aiming for here.

The one place where we currently have logging is for AWS requests. As you can see below. It has the idea of write once, works everywhere. It doesn't matter what AWS request we are making, the logging system works across the board for ALL AWS requests. Without any additional effort from us. Which is really what we are aiming for.

https://github.com/dynamoose/dynamoose/blob/255485328e33cfceac5d543f368b2bf4ca4de0dc/lib/aws/ddb/internal.ts#L29-L31

**Comment by arnoldsi-vii** [comment]
Hi,
Thank you for your response. From what I saw you already have the callback function with the error and request: 
(error, request) =>  {}

I thought It would be possible to check if there is an error and then log it to log.error.

**Comment by fishcharlie** [comment]
@arnoldsi-vii We aren't on the same page. This is normally why we require users submitting issues to fill out the entire issue template when submitting issues. What code do you have? What isn't working? Are you using the default console logger or a custom one? Is this specifically related to `ExpressionAttributeNames must not be empty`?  Where are you seeing `(error, request) => {}`?

Will be closing this issue since there isn't enough detail here.

**Comment by arnoldsi-vii** [comment]
@fishcharlie I think you misunderstood the dissection. I'm not reporting an issue, but asking about global error handler which can work with the callback function that you sending (with error and request). This way applications that using dynamoose will be able to log exceptions only and track the reason for it for better handling.
