### ISSUE TITLE
Update items in array[BUG]

### ISSUE THREAD

**Issue by coolshrimps** [dynamoose/dynamoose#1122]
### Summary:

I query by ID and fetch the results. I want to update an attribute whose type is an array. I push a new record into the array and update the table. But I get an error when the array's size is larger than 1.

Also I cannot find /node_modules/dynamoose/lib in my folder.

TypeError: Cannot destructure property 'customType' of 'typeDetails' as it is undefined.
    at .../node_modules/dynamoose/lib/Document.ts:376:12
    at Array.map (<anonymous>)
    at Function.Document.objectFromSchema (.../node_modules/dynamoose/lib/Document.ts:371:62)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at Object.keys.reduce.Promise.resolve.obj.ExpressionAttributeNames (.../node_modules/dynamoose/lib/Model/index.ts:733:19)
    at getUpdateExpressionObject (.../node_modules/dynamoose/lib/Model/index.ts:707:25)
    at .../node_modules/dynamoose/lib/Model/index.ts:888:90

### Code sample:

  mytable.query("id").eq(req.params.id).exec((error, results) => {
      if(error) {
          console.log(error);
          res.status(400).send({ status: "error"});
      }
      else {
          if(results.count == null || results.count == 0) {
              res.status(400).send({ status: "error" });
              return;
          }
          else {
              let item = new newItem(); //newItem is also an schema of model
              results[0].list.push(item);
  
              mytable.update({
                  "brandID": results[0].id,
                  "BrandInventoryList": list      }
              , (error, user) => {
                  if (error) {
                      console.error(error);
                      res.status(400).send({ status: "error"});
  
                  } else {
                      console.log(user);
                      res.send({  status: "success"});
                  }
              });
               
          }
      }
  });

#### Schema
```
// Code here
```

#### Model
```
// Code here
```

#### General
```
// Code here
```

### Environment:

Operating System:
Operating System Version:
Node.js version (`node -v`):
NPM version: (`npm -v`):
Dynamoose version:

### Other:
- [ ] I have read through the Dynamoose documentation before posting this issue
- [ ] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [ ] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [ ] I have tested the code provided and am confident it doesn't work as intended
- [ ] I have filled out all fields above
- [ ] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
Thank you for your issue. This project is successful due to the reports and help we get from the community in improving the project.

This project has a lot of guidelines that help ensure the project continues to run smoothly and project maintainers aren't burdened with a lot of back and forth discussion in order to advance the project and resolve issues.

**Sadly it has been determined that your issue does not follow those guidelines.**

This could be due to the following *checked* items (unchecked items were satisfied, found irrelevant, or not checked):

General

- [x] Issue template not filled out
- [ ] Issue is unclear
- [ ] Issue doesn't explain what has already been tried and what attempts you have made to resolve the issue

Example (MCVE)

- [ ] Example provided has too much irrelevant code and is not considered minimal (*Minimal*)
- [x] Example provided has undefined variables that make it impossible to reproduce (*Complete*)
- [x] Example provided is missing code necessary to reproduce the error (*Complete*)
- [ ] When trying to reproduce example provided I did not receive the same error message as described in issue (*Verifiable*)
- [ ] No example provided (*Example*)

Error

- [ ] No error included
- [ ] Error included is unclear or confusing
- [ ] No stack trace included in error
- [ ] No information about current and expected result

Read through our [contributing guidelines](https://github.com/dynamoose/dynamoose/blob/master/CONTRIBUTING.md) for more information about what is expected when submitting issues.

If you have any questions about why this message was posted on your issue, please comment below with your specific question and we'd be happy to discuss with you further. If you believe you have followed the guidelines and still received this error message, please comment your reasoning below for why you believe you have followed the guidelines checked above, and we'll take another look at it.

While we understand that these guidelines create a larger burden on you, it is critical you follow them. The project maintainers have to handle everyone's issues while you only have to write yours, so it is imperative you make our jobs easier and help save us time by following the guidelines.

In order to proceed, please create a *new issue* ensuring you address all guidelines checked above (while also taking note to not violate any guidelines you followed).

---

Additional Information:

- No Environment information included
- `list` variable undefined
- No schema or model included in issue

> Also I cannot find /node_modules/dynamoose/lib in my folder

That is the expected behavior. Dynamoose uses TypeScript so it will only download the transpiled JS files and not include the TypeScript files.

---

Disclosure: This was based on a [GitHub Saved Reply](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/working-with-saved-replies). The checkboxes were manually checked by myself based on your original issue.
