### ISSUE TITLE
[BUG] Slow scan operations

### ISSUE THREAD

**Issue by Josefnm** [dynamoose/dynamoose#1260]
### Summary:

I'm using dynamoose for my project, and overall it works well. However scan operations are several times slower than the same operations using AWS DocumentClient. 

#### Schema
It's the same with all my different schemas. Here is an example of the simplest one. None of them use Buffer type.
```
const userSchema = new dynamoose.Schema(
  {
    id: {
      type: String,
      required: true,
      hashKey: true,
    },
    phoneNumber: {
      type: String,
      index: {
        project: true,
        global: true,
        name: 'UserPhoneNumberIndex',
      },
    },
    name: String,
    status: String,
    email: String,
    // a few more fields with strings, numbers and booleans
  },
  { timestamps: true }
)
```

#### Model
```
const model = dynamoose.model('myTable', mySchema, {
    create: false,
    waitForActive: false,
  })
```

#### General
```
// dynamoose
MyModel.scan().all().exec()

// DocumentClient
export const scanTable = async <T = unknown>(
  table: string,
  extraParams?: Partial<AWS.DynamoDB.DocumentClient.ScanInput>
): Promise<T[]> => {
  const params: AWS.DynamoDB.DocumentClient.ScanInput = {
    TableName: `${constants.ENV}-${table}`,
    ...extraParams,
  }

  const scanResults = []
  let response: PromiseResult<
    AWS.DynamoDB.DocumentClient.ScanOutput,
    AWS.AWSError
  >
  do {
    // eslint-disable-next-line no-await-in-loop
    response = await getDocumentClient().scan(params).promise()
    scanResults.push(...response.Items)
    params.ExclusiveStartKey = response.LastEvaluatedKey
  } while (typeof response.LastEvaluatedKey !== 'undefined')

  return <T[]>scanResults
}
```

### Current output and behavior (including stack trace):
Example 1:
Scanning ~450 items that are ~1 kb each (according to aws dynamodb console).
Using aws DocumentClient and scanning all: ~400 ms
Using dynamoose scan all: ~4500 ms

Example 2:
Scanning ~23000 items that are ~230 bytes each.
Using aws DocumentClient and scanning all: ~6000 ms
Using dynamoose scan all: ~24000 ms

### Expected output and behavior:

Somewhat similar performance

### Environment:

Operating System: Amazon Linux
Operating System Version: 2
Node.js version (`node -v`): v14.x
NPM version: (`npm -v`): 7.18.1
Dynamoose version: 2.8.1

### Other information (if applicable):

AWS lambda using the Serverless framework.

Serverless version: 2.48.0
aws sdk version: 2.952.0
AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

### Other:
- [ x ] I have read through the Dynamoose documentation before posting this issue
- [ x ] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [ x ] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [ x ] I have tested the code provided and am confident it doesn't work as intended
- [ x ] I have filled out all fields above
- [ x ] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
Curious about where this is occurring.

You mention this is related to scan operations. Are you confident that is the culprit?

I'm aware of this PR which caused high initialization times for Dynamoose: https://github.com/dynamoose/dynamoose/pull/1154. Could that potentially be the culprit? You could try the v3 alpha to see if that PR improves it.

I'm also aware of a change made recently to remove a cache that was causing memory leaks. That was related to parsing the document.

There is no doubt that I expect Dynamoose to have more overhead than AWS-SDK itself. More work is required to ensure schema conformance. However this performance hit shouldn't be excessive (as it looks to be in your example).

**Comment by fishcharlie** [comment]
@FanFataL Sadly that line is very critical and doesn't really lead to information about what is going wrong.

We kinda need to dive into that method and determine which part specifically is slowing things down.

As mentioned in my previous message, v3 alpha does make some improvements to performance. Are you able to try that and see if the issue persists?

**Comment by fishcharlie** [comment]
Closing since the latest report is that v3 alpha is on-par with native client.

**Comment by PaulAtST** [comment]
@fishcharlie Unfortunately I am seeing the same issue with v3, but now it's the lines:

```
const expectedObject = await Item.objectFromSchema(item, item.getInternalProperties(internalProperties).model, settings);
```

Speed wise I am using v3 being about 0.5 - 1.0 sec slower then v2 unfortunately. Is there a way to optimize querying for a list of objects? I am concerned this is not going to scale up to what I need for my use case.

**Comment by PaulAtST** [comment]
@fishcharlie Your welcome. 

I did some more digging into performance profiles for v3. Another slow spot I have identified is the function `deep_copy(obj)` inside the file `deep_copy.js`. In particular it's the call `objectUtils.isCircular(obj, attr)` which is slowing it down significantly. In my case removing that check is saving me abut 1.5 seconds. 

Is it possible for a return from DynamoDB to be circular? If not a possible solution can be adding a parameter to `deep_copy` to not do the circular check when making a copy of a return from DynamoDB. 

Also it looks like for each item in the return the line `"originalObject": utils_1.default.deep_copy(itemObject)` gets called. This can be another place to optimize with an item level cache. 

I will keep digging and see what else I find.

**Comment by jpblair** [comment]
I'm seeing what I think is similar behavior for at least `GetItem` operations, possibly others. Even when retrieving a single item, the deserialization process via `documentify()` can take on the order of seconds, depending on how complex/deeply nested the object is. By contrast, a serialization/deserialization using `JSON.parse(JSON.stringify(obj))` only takes 2ms. I only did some rough profiling, but it seems to point to some of the same culprits that @PaulAtST identified:

- `await Document.attributesWithSchema(returnObject, model).map(key => {`
- `await model.schemaForObject(returnObject)`
- The `settings.modifiers` block

Here is my schema:
```
const schema = new dynamoose.Schema(
  {
    revision_id: {
      type: String,
      required: true,
      hashKey: true,
      default: ArcUUID.create
    },
    collection_id: {
      type: String,
      required: true,
      rangeKey: true
    },
    parent_id: {
      type: String
    },
    org_id: {
      type: String,
      required: true
    },
    document: {
      type: Object,
      schema: {
        type: {
          type: String
        },
        headlines: {
          type: Object
        },
        description: {
          type: Object
        },
        content_aliases: {
          type: [String]
        },
        canonical_website: {
          type: String
        },
        websites: {
          type: Set,
          schema: [String]
        },
        query_backfill: {
          type: String
        },
        pinned_count: {
          type: Number,
          default: 0
        },
        content_elements: {
          type: Array,
          schema: [
            {
              type: Object,
              schema: {
                referent: {
                  type: Object,
                  schema: {
                    id: String,
                    type: String,
                    referent_properties: {
                      type: Object,
                      schema: {
                        headlines: {
                          type: Object
                        },
                        description: {
                          type: Object
                        },
                        promo_items: {
                          type: Object
                        }
                      }
                    }
                  }
                },
                type: String
              }
            }
          ]
        }
      }
    }
  },
  {
    timestamps: {
      createdAt: 'created_date',
      updatedAt: 'last_updated_date'
    },
    saveUnknown: true,
    useDocumentTypes: true,
    useNativeBooleans: true
  }
)
```
And attached is the sample document I'm trying to retrieve/deserialize: [sample.txt](https://github.com/dynamoose/dynamoose/files/9479755/sample.txt)

This is pretty major hindrance to our application, so please let me know of any mitigations/workarounds/alternatives/etc. Otherwise, I'd be interested to know what the timeline is for fixing this. Please let me know if a new ticket would be helpful. Thanks!

**Comment by ptejada** [comment]
@jpblair 

I know it might defeat the purpose of using a schema. but can you share the stats for getting your document in this two ways?

```js
const document = await Model.get({...})

// VS

const request = await Model.get({...}, {return: 'request'})
const document = await dynamoose.aws.ddb().getItem(request)
```

**Comment by tareqx2** [comment]
Having similar performance issues when performing a `model.query` for ~20k items. 
Using a dynamoose query takes around 20 seconds where as using a regular dynamo query takes 2 seconds

**Comment by jpblair** [comment]
@ptejada I tried this, and bypassing Dynamoose seems to shave off 600-700ms.

**Comment by tranhl** [comment]
@fishcharlie I can confirm that `deep_copy` is taking a significant performance toll when querying data sets and objects. I have provided a repository that provides a small reproducible example using DynamoDB Local. As @PaulAtST has identified in [this comment](https://github.com/dynamoose/dynamoose/issues/1260#issuecomment-1176351422), `deep_copy` is the primary culprit, due to the [objectUtils.isCircular](https://github.com/dynamoose/dynamoose/blob/fd010ebda6c006aed63756a828ed6f978f6ba410/packages/dynamoose/lib/utils/deep_copy.ts#L56) call. While `deep_copy` is coping the source object, it calls `isCircular` to check whether encountered objects contain circular references. This is essentially an `O(n^2)` operation, as the `isCircular` function will **also** traverse the object in order to determine whether circular references exist.

Instead of relying on `isCircular` to detect and omit circular references, we should instead handle this ourselves within `deep_copy`, so that we only traverse the input object once. The provided reproduction repository contains a patched version of Dynamoose that does this, with the profiling results speaking for themselves.

**Comment by PaulAtST** [comment]
@tranhl Nice work! Sounds like a solid approach to me.
