### ISSUE TITLE
[FEATURE] come back updateTimestamps option

### ISSUE THREAD

**Issue by tomofumi0003** [dynamoose/dynamoose#1278]
### Summary:
I still use dynamoose v1 (great thanks).
I tried to migrate v1 to v2 but I cannot migrage v1 to v2 because save method cannot use updateTimestamps option.
I seem updateTimestamps option is exist in current source.
Is it possible to come back the updateTimestamps option to the save method?

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this feature has not already been suggested before
- [x] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

**Comment by tomofumi0003** [comment]
@fishcharlie No. My goal is to put the item with the specified "created_at" (not now).

**Comment by fishcharlie** [comment]
@tomofumi0003 Any reason you don't just use a custom date property?

**Comment by fishcharlie** [comment]
@tomofumi0003 That makes sense, but it doesn't answer my question at all. Why can't you just make a property in your schema that is a date type? Why do you need to use the timestamps feature at all?

**Comment by tomofumi0003** [comment]
@fishcharlie I am sorry about that.

> Why can't you just make a property in your schema that is a date type?
Because my app is already in operation, it is difficult to modify code. (I can, but difficult)

> Why do you need to use the timestamps feature at all?
I think multiple columns with the same value/meaning are redundant.

Is this the answer?

**Comment by fishcharlie** [comment]
@tomofumi0003

> it is difficult to modify code

Not difficult at all. Sounds like in your database your createdAt attribute is called `created_at`.

So in v2 of Dynamoose, just make your schema look like:

```js
new dynamoose.Schema({
    "created_at": {
        "type": Date,
        "required": true
    }
}, {
    "timestamps": false // Technically you don't need this since the default is `false`, but adding this here to show that you don't need to use timestamps and to make the code here more clear
});
```

That way you can read existing documents with the same attribute, and for new documents, just set `created_at` to be the value you want (either the current time, or the different time due to network error). Fully customizable, nothing to do. All you have to do is make sure you set `created_at` whenever you create a new item. Dynamoose won't do it for you automatically anymore.

If you want Dynamoose to do it for you still, you could look into the [`default` setting](https://dynamoosejs.com/guide/Schema#default-value--function--async-function).

> I think multiple columns with the same value/meaning are redundant.

No properties/columns with the same value/meaning in the example I just gave. You are just changing it from using Dynamoose timestamps, to your own property that you control. Documents/items you save will be the same, but you just have more control (which does mean you need to handle setting it yourself, but you get more flexibility that way).

---

Hopefully that helps you and makes sense. Let me know if you have any other questions.

**Comment by fishcharlie** [comment]
@tomofumi0003 Awesome. I'm gonna close this for now. Let me know if you have any other questions.
