### ISSUE TITLE
[BUG] $ADD to StringSet fails on single string value

### ISSUE THREAD

**Issue by half2me** [dynamoose/dynamoose#1285]
### Summary:

```
await MyModel.transaction.update({ id: 'foo' }, { $ADD: { myset: 'foobar', version: 1 } }), // fails
await MyModel.transaction.update({ id: 'foo' }, { $ADD: { myset: ['foobar'], version: 1 } }), // succeeds
```

I haven't tested it outside of a transaction, so I don't know if it affects all `update()` commands, or only ones in a transaction. Current workaround is to always use `[]` even when adding a single item to a set.

#### Model
```
myset: {
  type: Set,
  schema: [String],
},
version: Number,
```

### Environment:

Dynamoose version: v3

**Comment by fishcharlie** [comment]
Thank you for your issue. This project is successful due to the reports and help we get from the community in improving the project.

This project has a lot of guidelines that help ensure the project continues to run smoothly and project maintainers aren't burdened with a lot of back and forth discussion in order to advance the project and resolve issues.

**Sadly it has been determined that your issue does not follow those guidelines.**

This could be due to the following *checked* items (unchecked items were satisfied, found irrelevant, or not checked):

General

- [x] Issue template not filled out
- [ ] Issue is unclear
- [ ] Issue doesn't explain what has already been tried and what attempts you have made to resolve the issue

Example (MCVE)

- [ ] Example provided has too much irrelevant code and is not considered minimal (*Minimal*)
- [ ] Example provided has undefined variables that make it impossible to reproduce (*Complete*)
- [ ] Example provided is missing code necessary to reproduce the error (*Complete*)
- [ ] When trying to reproduce example provided I did not receive the same error message as described in issue (*Verifiable*)
- [ ] No example provided (*Example*)

Error

- [x] No error included
- [ ] Error included is unclear or confusing
- [x] No stack trace included in error
- [x] No information about current and expected result

Read through our [contributing guidelines](https://github.com/dynamoose/dynamoose/blob/master/CONTRIBUTING.md) for more information about what is expected when submitting issues.

If you have any questions about why this message was posted on your issue, please comment below with your specific question and we'd be happy to discuss with you further. If you believe you have followed the guidelines and still received this error message, please comment your reasoning below for why you believe you have followed the guidelines checked above, and we'll take another look at it.

While we understand that these guidelines create a larger burden on you, it is critical you follow them. The project maintainers have to handle everyone's issues while you only have to write yours, so it is imperative you make our jobs easier and help save us time by following the guidelines.

In order to proceed, please create a *new issue* ensuring you address all guidelines checked above (while also taking note to not violate any guidelines you followed).

---

Additional Information:

Additionally need to know the following.

- Is specific to v3 alpha or does it apply to v2 as well?
- What version of v3 alpha are you running?

---

Disclosure: This was based on a [GitHub Saved Reply](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/working-with-saved-replies). The checkboxes were manually checked by myself based on your original issue.

**Comment by half2me** [comment]
You can close the issue, but the bug is still there 🤷‍♂️

**Comment by fishcharlie** [comment]
@half2me Goal isn't to close issues that exist and are still impacting customers, but to ensure we have the information to easily resolve and reproduce issues.

As mentioned in the comment. Please feel free to create a new issue and take note of the issue template and the checked items in the comment above. This will help save us time and resolve your issue quicker.
