### ISSUE TITLE
[FEATURE] Short circuit evaluation for conditions

### ISSUE THREAD

**Issue by fengyuli2002** [dynamoose/dynamoose#1327]
### Summary:

The following code will produce an error when an object does not have availability.Fri.
This is not ideal because intuitively, the first line should have already checked this and result in an early termination of the condition.
```typescript
  const condition = new Condition(`availability.${getDay()}`).exists().and()
    .where(`availability.${getDay()}`).eq('something')
```

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue

**Comment by fishcharlie** [comment]
Thank you for your issue. This project is successful due to the reports and help we get from the community in improving the project.

This project has a lot of guidelines that help ensure the project continues to run smoothly and project maintainers aren't burdened with a lot of back and forth discussion in order to advance the project and resolve issues.

**Sadly it has been determined that your issue does not follow those guidelines.**

This could be due to the following *checked* items (unchecked items were satisfied, found irrelevant, or not checked):

General

- [x] Issue template not filled out
- [x] Issue is unclear
- [ ] Issue doesn't explain what has already been tried and what attempts you have made to resolve the issue

Example (MCVE)

- [ ] Example provided has too much irrelevant code and is not considered minimal (*Minimal*)
- [ ] Example provided has undefined variables that make it impossible to reproduce (*Complete*)
- [x] Example provided is missing code necessary to reproduce the error (*Complete*)
- [ ] When trying to reproduce example provided I did not receive the same error message as described in issue (*Verifiable*)
- [x] No example provided (*Example*)

Error

- [x] No error included
- [ ] Error included is unclear or confusing
- [x] No stack trace included in error
- [x] No information about current and expected result

Read through our [contributing guidelines](https://github.com/dynamoose/dynamoose/blob/master/CONTRIBUTING.md) for more information about what is expected when submitting issues.

If you have any questions about why this message was posted on your issue, please comment below with your specific question and we'd be happy to discuss with you further. If you believe you have followed the guidelines, please comment your reasoning below for why you believe you have followed the guidelines checked above, and we'll take another look at it.

While we understand that these guidelines create a larger burden on you, it is critical you follow them. The project maintainers have to handle everyone's issues while you only have to write yours, so it is imperative you make our jobs easier and help save us time by following the guidelines.

In order to proceed, please create a *new issue* ensuring you address all guidelines checked above (while also taking note to not violate any guidelines you followed).

---

Additional Information:



---

Disclosure: This was based on a [GitHub Saved Reply](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/working-with-saved-replies). The checkboxes were manually checked by myself based on your original issue.
