### ISSUE TITLE
[BUG] Schema not enforced for `Object` fields when `saveUnknown = false`

### ISSUE THREAD

**Issue by darrenrahnemoon** [dynamoose/dynamoose#1436]
### Summary:
I have the following schema:
```
const schema = new Schema({
	id: {
		type: String,
		hashKey: true,
	},
	name: {
		type: Object,
		default: { first: '', last: '' },
		schema: {
			first: String,
			last: String,
		},
	},
	phone: Number
	}, 
{ saveUnknown: false, useDocumentTypes: false })
```
When I perform an update using the following:
```
model(tableName, schema).update({ id : id }, { name : { middle : 'Shouldn't save' } })
```

### Current output and behavior (including stack trace):
The data does save with no errors but it also saves `middle` which was not defined in the schema even though `saveUnknown` is set to `false`.

### Expected output and behavior:
The `middle` field in `name` not be saved since 

We do run an older version and unfortunately upgrading would be costly for us. Do you think that is the reason we're facing this issue?

### Environment:
Operating System: Serverless (AWS lambda)
Operating System Version: 1.6.1
Node.js version (`node -v`): v14.5.0
NPM version: (`npm -v`): 7.24.2
Dynamoose version: ^1.6.5

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [x] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [x] I have tested the code provided and am confident it doesn't work as intended
- [x] I have filled out all fields above
- [ ] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
@darrenrahnemoon Hate to say this. But I have no idea. I haven't used v1 of Dynamoose in an extremely long time. It's no longer supported at all. Like even if a security vulnerability were to be found in v1, we would not patch it.

> Do you think that is the reason we're facing this issue?

I do think it's possible yes. When v2 was released, I was aware of some bugs in v1. I forget what all of those were, but bugs for sure exist in the v1 line.

---

One thing you could try. Is I'm pretty sure `Object` as a type isn't the same in v1 as v2. You could try changing your type to `"Map"`, to see if that improves things.

Additionally, your syntax (minus the `useDocumentTypes` setting), is v2 Dynamoose syntax. The documentation for v1 of Dynamoose isn't great, but `schema` I don't think is a valid option on v1 Dynamoose. I just quickly looked through the v1 code, and I don't see anywhere where `schema` property on an attribute exists. Where did you come up with that code?

Finally, in this code:

https://github.com/dynamoose/dynamoose/blob/9e5fb1605e99da2d5550cfa896d224c09aaa3cc8/lib/Schema.js#L169-L172

It looks like it's just passing the entire object into the attribute. Based on that code I'm not even sure Dynamoose v1 supports type checking nested attributes. Do you have some evidence that it does? Seems like this might be more of a feature request than a bug.

---

Besides that, I can't really help any further. I strongly recommend upgrading to v2. I understand that it's a major upgrade. But v1 really isn't supported anymore. Feel free to also fork the code for v1, and make the necessary changes to fit your use case, add features, or fix bugs.

Going to close this issue since v1 is not supported anymore.
