### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'ddb')

### ISSUE THREAD

**Issue by nimit2801** [dynamoose/dynamoose#1478]
### Summary:

I've been trying to use Dynamoose with AWS DynamoDB, but I'm getting this error. 
`TypeError: Cannot read properties of undefined (reading 'ddb')`
I don't know why this error is coming. It should just read ddb

### Code sample:
```js
import * as Dynamoose from 'dynamoose';
import dotenv from 'dotenv';

dotenv.config();
let accessKeyId = process.env.accessKeyId;
let secretAccessKey = process.env.secretAccessKey;
let region = process.env.region;
const ddb = new Dynamoose.aws.ddb.DynamoDB({
  accessKeyId,
  secretAccessKey,
  region,
});
Dynamoose.aws.ddb;
Dynamoose.aws.ddb.set(ddb);
const UserSchema = new Dynamoose.Schema({
  uuid: { type: String, required: true },
  sortkey: { type: String, required: true },
  userName: String,
  firstName: String,
  lastName: String,
  email: String,
  phoneNumber: Number,
  address: String,
});

const User = Dynamoose.model('User', UserSchema);

try {
  let newUser = new User({
    uuid: 'd4c0b86c-8cba-4423-8635-edc9e0dc0abc',
    sortkey: 'user/Nimit2801',
    userName: 'Nimit2801',
    firstName: 'Nimit',
    lastName: 'Savant',
    email: 'mnimitsavant@outlook.com',
    phoneNumber: '9664707262',
    address: 'Vadodara',
  });
  newUser.save();
} catch (error) {
  console.log(error);
}
```

### Current output and behavior (including stack trace):

![image](https://user-images.githubusercontent.com/53462249/186278610-82899fd6-4542-40e3-b721-e5a64338250f.png)

### Expected output and behavior:
Should give me out where it either saves or rejects the query

### Environment:

Operating System:
Operating System Version: Windows 10
Node.js version (`node -v`): v16.13.1
NPM version: (`npm -v`): 8.5.5
Dynamoose version: 3.0.0

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [x] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [x] I have tested the code provided and am confident it doesn't work as intended
- [x] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
@nimit2801 What happens if you `console.log(Dynamoose.aws)` right before that error? Or `console.log(Dynamoose)` even. Just trying to figure out what exactly is going on here.

**Comment by nimit2801** [comment]
Code 1 for `console.log(Dynamoose)`
```js
import * as Dynamoose from 'dynamoose';
import dotenv from 'dotenv';

dotenv.config();
let accessKeyId = process.env.accessKeyId;
let secretAccessKey = process.env.secretAccessKey;
let region = process.env.region;
// const ddb = new Dynamoose.aws.ddb.DynamoDB({
//   accessKeyId,
//   secretAccessKey,
//   region,
// });
console.log(Dynamoose);
```
Output 1

![image](https://user-images.githubusercontent.com/53462249/186487648-afccc0de-fe06-49d2-8e08-b8525a095680.png)


Code 2 for `console.log(Dynamoose.aws)`
```js
import * as Dynamoose from 'dynamoose';
import dotenv from 'dotenv';

dotenv.config();
let accessKeyId = process.env.accessKeyId;
let secretAccessKey = process.env.secretAccessKey;
let region = process.env.region;
// const ddb = new Dynamoose.aws.ddb.DynamoDB({
//   accessKeyId,
//   secretAccessKey,
//   region,
// });
console.log(Dynamoose.aws);
```
Output 2
![image](https://user-images.githubusercontent.com/53462249/186487785-4f762e2b-f227-4b4b-845e-963fe1951a3f.png)

**Comment by fishcharlie** [comment]
Thank you for your issue. This project is successful due to the reports and help we get from the community in improving the project.

This project has a lot of guidelines that help ensure the project continues to run smoothly and project maintainers aren't burdened with a lot of back and forth discussion in order to advance the project and resolve issues.

**Sadly it has been determined that your issue does not follow those guidelines.**

This could be due to the following *checked* items (unchecked items were satisfied, found irrelevant, or not checked):

General

- [ ] Issue template not filled out
- [ ] Issue is unclear
- [ ] Issue doesn't explain what has already been tried and what attempts you have made to resolve the issue

Example (MCVE)

- [x] Example provided has too much irrelevant code and is not considered minimal (*Minimal*)
- [ ] Example provided has undefined variables that make it impossible to reproduce (*Complete*)
- [ ] Example provided is missing code necessary to reproduce the error (*Complete*)
- [x] When trying to reproduce example provided I did not receive the same error message as described in issue (*Verifiable*)
- [ ] No example provided (*Example*)

Error

- [ ] No error included
- [ ] Error included is unclear or confusing
- [ ] No stack trace included in error
- [ ] No information about current and expected result

Read through our [contributing guidelines](https://github.com/dynamoose/dynamoose/blob/master/CONTRIBUTING.md) for more information about what is expected when submitting issues.

If you have any questions about why this message was posted on your issue, please comment below with your specific question and we'd be happy to discuss with you further. If you believe you have followed the guidelines, please comment your reasoning below for why you believe you have followed the guidelines checked above, and we'll take another look at it.

While we understand that these guidelines create a larger burden on you, it is critical you follow them. The project maintainers have to handle everyone's issues while you only have to write yours, so it is imperative you make our jobs easier and help save us time by following the guidelines.

In order to proceed, please create a *new issue* ensuring you address all guidelines checked above (while also taking note to not violate any guidelines you followed).

---

Additional Information:

I tried to reproduce this with the following TypeScript code:

```ts
import * as Dynamoose from "dynamoose";

console.log(Dynamoose.aws.ddb);

const ddb = new Dynamoose.aws.ddb.DynamoDB({
	"region": "us-west-2"
});
```

And I get the following result:

```
[Function: func] {
  DynamoDB: [class DynamoDB extends DynamoDBClient],
  set: [Function (anonymous)],
  revert: [Function (anonymous)],
  local: [Function (anonymous)]
}
```

Everything looks fine to me.

---

Disclosure: This was based on a [GitHub Saved Reply](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/working-with-saved-replies). The checkboxes were manually checked by myself based on your original issue.

**Comment by nimit2801** [comment]
Thank you, I'll try with TS once and if the issues still remain I'll open a new issue :)
