### ISSUE TITLE
[FEATURE] Testing support

### ISSUE THREAD

**Issue by dolsem** [dynamoose/dynamoose#840]
### Summary:
Testing OLTP applications that use DynamoDB as the primary database is a bit awkward right now and requires extra bells and whistles to make sure there are no data collisions. Imagine a hypothetical scenario for a game application where high score is stored on the user object. You have one test which updates user's high score and sends a notification letting the user know they're #1 on the leaderboard. You have another test that populates the leaderboard - scans the table and returns the users with the highest score. It's really tricky to write these tests in a way to prevent all possible data collisions and make them succeed deterministically.

In Rails there's a popular FactoryBot library that works nicely with Rspec (testing framework) and makes it really easy to work with mock data. You define your mock data in the global scope at the top of your test suite, and then just reference these variables in each of your tests, but the variables will actually contain different copies of data inside of each test and data collision almost never happens.

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this feature has not already been suggested before
- [x] I have filled out all fields above
- [ ] I am running the latest version of Dynamoose

---

**Describe the solution you'd like**
Something like this can be done with DynamoDB, though due the specifics of its architecture the only reliable way to avoid collisions is to create a separate table for each test suite. Here's how I think this could work.

First, there should be a config option (not sure if it already exists or not) to assume all database tables are fully set up and skip checks when we call `dynamoose.model()`. We won't need these tables in the test environment.

Second, we can have a function, something like `dynamoose.factory()`, that takes a Dynamoose model as the first argument and a function as the second. It creates a table prefixed with `Date.now()` timestamp and returns a wrapper for that model that for all intents and purposes behaves like the actual reference to the Dynamoose model, except that you should be able to just run `Model.create()` with no arguments and it will create a perfectly valid instance for you using this factory function. The factory function takes two arguments provided by Dynamoose, `create` function (don't confuse with the aforementioned `Model.create()`) and index.

Here's how this would look in practice:

```ts
// test/factories.ts
import * as _ from 'lodash';
import * as dynamoose from 'dynamoose';
import { User, Note } from '../src/models'; 
export const userFactory: dynamoose.FactoryFunc<User> = async (create, index) => {
  const item = await create({
    name: `User ${index+1}`,
    company: [
      _.sample(['Silver', 'Crystal', 'Ocean']),
      _.sample(['Enterprises', 'Productions', 'Security', 'Technologies']),
    ].join(' ');
    await item.customMethod();
});
export const noteFactory: dynamoose.FactoryFunc<Note> = (create, index) => create({ name: `Note #${index+1}` }));
export const nullFactory = () => null;

// test/my-test.ts
import * as dynamoose from 'dynamoose';
import { User, Note } from '../src/models'; 
import { userFactory, noteFactory, nullFactory } from './factories';
let UserFactory: dynamoose.Factory<User>;
let NoteFactory: dynamoose.Factory<Note>;
let CustomNoteFactory: dynamoose.Factory<Note>;
let NullFactory: dynamoose.Factory<Note>;
let userA: User;
let userB: User;
let noteA: Note;
let noteB: Note;
let noteC: Note;

beforeEach(() => {
  UserFactory = dynamoose.factory(User, userFactory); // creates '1587779245702_User' table
  NoteFactory = dynamoose.factory(Note, noteFactory); // creates '1587779245756_Note' table
  CustomNoteFactory = dynamoose.factory(Note, (create, index) => create({ name: `Note ${String.fromCharCode(65 + index)}` }), `${Date.now()}-CustomNote` ); // creates '1587779245805-CustomNote' table
  NullFactory = dynamoose.factory(Note, nullFactory); // creates '1587779245913_Note' table
  userA = new UserFactory(); // User { name: 'User 1', company: 'Ocean Enterprises' }
  userB = new UserFactory({ name: 'Custom User Name' }); // User { name: 'Custom User Name', company: 'Crystal Technologies' }
  noteA = new NoteFactory(); // Note { name: 'Note #1' }
  noteB = new NoteFactory(); // Note { name: 'Note #2' }
  noteC = new CustomNoteFactory(); // Note { name: 'Note A' }
  new NullFactory({ name: 'My Note' }); // returns null and never creates an instance of the item, because the `create` function never gets called inside the factory function. This shows that if the factory function returns something other than undefined, the factory will be set to that value.
});

afterEach(() => {
  NullFactory.destroy(); // Deletes the table created for this factory
});

it('works', async () => {
  noteA.name = 'New Note';
  await Promise.all([UserFactory.sync(), NoteFactory.sync(), CustomNoteFactory.sync()]); // Note that this is where the items actually get saved to the database. This lets us overwrite values for individual tests, like what we did here with noteA.
  console.log(noteA); // Note { name: 'New Note' });
  console.log(noteB); // Note { name: 'Note #2' });
});

it('also works', async () => {
  await dynamoose.factory.sync(UserFactory, NoteFactory, CustomNoteFactory); // Alternative syntax for saving everything to the database.
  console.log(noteA); // Note { name: 'Note #1' }
  console.log(noteB); // Note { name: 'Note #2 } <- Note that even though this object has the same data as in the first test, it is stored in a brand new table, created in the beforeEach hook iteration for this specific test
});

afterAll(() => {
  dynamoose.factory.destroyAll(); // Deleted tables for all remaining factories
});
```

**Describe alternatives you've considered**
This can either be implemented as a core Dynamoose functionality, or it can be its own library, something like 'dynamoose-factory', whatever makes most sense. I would actually probably prefer it to be a separate library as this will reduce the size of the production bundle. However, in order to implement this as an external library, it should be possible to interact with Dynamoose's internals in a way that can achieve this.

**Comment by fishcharlie** [comment]
@dolsem Amazing summary here. Few questions that initially come to mind:

1. You mention `Note that this is where the items actually get saved to the database` and also mention about creating tables. But is there actually a DynamoDB Local instance running in this case? Or is this more of a mock situation where it's saving to some mock array or something that acts as the database?
2. There is a `dynamoose.factory.destroyAll` method you mention, what about a `dynamoose.factory.syncAll` method? Would that be useful?
3. For `noteA = new Note();` is that supposed to be `noteA = new NoteFactory();`?
4. In the `userFactory`, is `item` then an instance of a User Document? Or what is the type of `item`?
5. What happens if you want to test query, scan, update, or get functionality? The example provided only seems to go over creating new items/documents.

---

Then replying to a few things:

> First, there should be a config option (not sure if it already exists or not) to assume all database tables are fully set up and skip checks when we call dynamoose.model(). We won't need these tables in the test environment.

Couldn't we just recommend setting `dynamoose.model.defaults = {"create": false};` in test model? Or are we still concerned that the model level options will overwrite the defaults here?

> This can either be implemented as a core Dynamoose functionality, or it can be its own library, something like 'dynamoose-factory', whatever makes most sense. I would actually probably prefer it to be a separate library as this will reduce the size of the production bundle. However, in order to implement this as an external library, it should be possible to interact with Dynamoose's internals in a way that can achieve this.

Totally agree with it being a separate library. `dynamoose` is normally considered a `dependency` and `dynamoose-factory` would likely be considered a `devDependency`. I don't see the value in adding blot to a production build for functionality that is limited to testing.

I do think this project should be managed by the [dynamoose GitHub organization](https://github.com/dynamoose) tho to ensure compatibility and such.

**Comment by dolsem** [comment]
@fishcharlie yes, actually, `dynamoose.setDefaults({ create: false })` is precisely what I meant, I forgot that this was an option. Also, for my current use case it seems to be enough to just use something like ```if (NODE_ENV === 'test') dynamoose.setDefaults({ prefix: `Test(${Date.now()})_` })```, which is awesome, because it's super easy. Of course it only works when data conflicts are between different test suites, not between different tests within the same suite, as it is in my aforementioned example.

To answer your questions:
1. Personally I do end-to-end tests and try to stub as few things as possible to get closer to what the production environment is like. So yes, the assumption was that a DynamoDB Local instance was running. I do this by spinning up a Docker container inside npm script 'pretest'. So when you do 'npm test' it starts the DynamoDB instance. Alternatively DynamoDB calls can be stubbed in AWS SDK, which might be worth doing at some point if Dynamoose users start requesting this feature.
2. `syncAll` won't be so useful because there will be a different set of factories each time the beforeEach hook is called, which is why we need to pass factories explicitly. Unless tests are run sequentially and `destroyAll()` is called in the afterEach hook. Still this would introduce a lot of potential for user mistakes and confusion. This can certainly be done if factories are grouped together explicitly and Dynamoose is made aware of this grouping. I am not too sure about the utility of this, it might overcomplicate the API unnecessarily.
3. Yes, thank you, I updated my example.
4. Yes, in TS terms, the function has a type `FactoryFunc<T extends dynamoose.Model>` and `create` has a type `Parameters<typeof T.prototype.create>[0] => Promise<T>`.
5. I think it should behave like a regular model would.

**Comment by fishcharlie** [comment]
@dolsem What I have found works well in the past as well is just deleting all the data from all of my tables in a `beforeEach`. Now that sucks because it takes time, and slows down your tests from what I've found (tho haven't actually determined how much). I tended to do this in a `beforeEach` hook at the global level of my tests, so even for minor tests that don't even touch the DB, it did this. Which is wildly inefficient and needs some refactoring, but yeah...

```js
beforeEach(async () => {
    const models = Object.values(require("./models")); // Assuming you have a file `./models/index.js` that has an object with each value referencing a model that you use
    const documents = _.flatten(await Promise.all(models.map((model) => model.scan().all().exec()))); // Should be all the documents in all of your models
    await Promise.all(documents.map((document) => document.delete())); // Delete all the documents in `documents`
});
```

Now in terms of your comment about data conflicts between tests. I wonder if you could clear the require cache between tests. Something like [clear-require](https://www.npmjs.com/package/clear-require) maybe? That **should** make it so next time you `require` your model, it gets reinitialized. Tho there might be some weird caching on Dynamoose's end here which should be fixed. So doing that with `deleteTable` AWS-SDK method, or doing that with the timestamp method you mentioned above with the model defaults, should work. Not sure what is the better way to do it. I'd probably lean towards `deleteTable` to ensure you don't have a bunch of useless tables sitting around.

Ideally, your tests should be all independent and should return to original state after done and setup before. [This page](https://glebbahmutov.com/blog/how-to-correctly-unit-test-express-server/) talks about that in terms of the context of Express.js (ie. shutting down the server after each test, clearing the require cache, etc.), but the same concepts apply.

Just trying to get a clearer picture of what exactly is the purpose and use case of this, and if some of the things mentioned about wouldn't achieve the same goal here. The things I mentioned above are a lot simpler than adding complexity to Dynamoose and have worked extremely well for me.

**Comment by dolsem** [comment]
@fishcharlie right, there are workarounds for this as long as your tests get executed one at a time, though most are slow. I find that instead of cleaning data all the time we can just launch DynamoDB Local with the -inMemory arg, create a bunch of tables and shut it down, and it will be destroyed anyway. This seems to be faster, simpler, and allows you to run tests in parallel (which is what frameworks like Jest do by default to speed up execution)

**Comment by fishcharlie** [comment]
@dolsem The problem I'm struggling with to grasp here, is it seems like this proposal is adding a lot of complexity for one specific use case. It seems like there should be a simpler way to allow for this and meet the requirements, without adding this much complexity to the underlying package.

The other potential that you could do, is use `if (NODE_ENV === 'test') dynamoose.setDefaults({ prefix: "Test(${Date.now()})_" })` along with setting your models to be wrapped in functions.

So for example. Your model would go from:

```js
module.exports = dynamoose.model("User", schema);
```

to

```js
module.exports = () => dynamoose.model("User", schema);
```

Then that allows you every test (in your `beforeEach` or something) to call the model function, and have it generate a new model with your prefix/suffix to ensure you have a clean model.

Or am I still missing something here?

**Comment by dolsem** [comment]
> Then that allows you every test (in your beforeEach or something) to call the model function, and have it generate a new model with your prefix/suffix to ensure you have a clean model.

@fishcharlie possible, as long as Dynamoose supports this way of doing it. Idk if it plays well right now with defining models on the go like that, and whether keeping them all, not unloading after each test, may result in slow performance / high memory usage. Also, my proposed API has a few other niceties baked in, that the user will otherwise have to implement themselves and make sure everything works well with TypeScript. Namely, the ability to define test data once in the outer scope and then override certain values for each test individually, as well as automatically setting values when they are not provided. But I agree, this API can definitely be simplified.

**Comment by fishcharlie** [comment]
@dolsem If you have time, I'd love to see your ideas for a simpler API here. For me, it seems like a great idea. I don't think it should be part of the core library tho since it has nothing to do with production level code.

The only consideration here, is how it'll work, and if it's something that will have enough benefits to where I'd be willing to maintain it. I'm struggling currently to see that it provides enough benefits to warrant the LOE of maintaining it.

If you'd be interested tho, I'd totally consider creating a repo under this organization and having you run this project.

I guess my point is that this is low on my priority list as of right now (especially since there are other ways to do it natively). So although it's a cool idea, and I'd love to see it done, it doesn't really fit into my current roadmap and plans I have at this time. If someone else would like to take charge of making this happen, totally willing to support that tho.
