### ISSUE TITLE
[QUESTION] How to add not equal to condition in conjunction with scan

### ISSUE THREAD

**Issue by prcongithub** [dynamoose/dynamoose#844]
I am trying to run a scan on a table with 3 conditions. But I am not able to find the right way to do this.
I want to do something like this:
```
Table.scan({
    field1: { eq: field1_value },
    field2: { eq: field2_value },
    status: { 'ne': 'archived' }
  })
```
### Environment:

Operating System:  Amazon Linux
Operating System Version:  No idea
Node.js version (`node -v`): 12.x
NPM version: (`npm -v`):     No idea
Dynamoose version: 2.0.0

#######
I have a workaround to this by using the below query:
```
Table.scan({
    field1: { eq: field1_value },
    field2: { eq: field2_value },
    status: { 'in': ['created','sent'] }
  })
```

**Comment by fishcharlie** [comment]
@prcongithub Can you try the following and let me know if it works?

```js
Table.scan("field1").eq(field1_value).where("field2").eq(field2_value).where("status").not().eq("archived")
```

Is your original code giving you an error? Or what is the problem?

**Comment by MickL** [comment]
Are you sure scan is the right choice? Why not query on a secondary index? Might be much more performant and cost efficient.

**Comment by fishcharlie** [comment]
@MickL is correct. `Scan` looks through each document before applying filters. `Query` can optimize this by partitioning your data, which can make this much more efficient. Of course, I don't know enough detail about your situation. Maybe there is a valid use case here for `Scan`. But `Query` is worth at least looking into as @MickL said.

It's likely the underlying question you have tho, applies to both `Scan` & `Query` since the majority of the code is shared between the two. So I still think your original question is valid. But do need more information in order to help answer the question.
