### ISSUE TITLE
How to set ttl value explicitly in dynamoose v1.11.1

### ISSUE THREAD

**Issue by Meghadi** [dynamoose/dynamoose#861]
### Summary:

I am using dynamoose 1.11.1 version. Trying to set ttl value for each row but the ttl value is set by default.
Can we set ttl value to few minutes ie 10mins.

### Code sample :
transaction.ttl = 60 *10
#### Schema
expires: {
            ttl: null, 
            attribute: 'ttl',
            returnExpiredItems: false,
        }
// Code here
```

#### Model
```
// Code here
```

#### General
```
// Code here
```


### Environment:

Operating System:Linux
Operating System Version:18.04
Node.js version (`node -v`):
NPM version: (`npm -v`):
Dynamoose version:1.11.1


### Other information (if applicable):




### Other:
- [yes ] I have read through the Dynamoose documentation before posting this issue
- [ yes] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this question has not already been raised before
- [ ] I have searched the internet and Stack Overflow to ensure this question hasn't been raised or answered before
- [ ] I have filled out all fields above
- [ ] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
👋 @Meghadi. Thanks for submitting this question!!

Basically in order to do this you must set `ttl` to a default time. Then when creating or modifying your documents/items, you can set that property to be whatever you want. The `ttl` property is required, so you are not allowed to use `null`, but it is only a default. This means you can overwrite it at the document level.

---

On a different note, I'd highly recommend upgrading to v2. This is something that could potentially be improved in v2 in the future (so stay tuned to the release notes). The v1.x.x version is highly unlikely to get any further updates. The only exception to this would be if a major security vulnerability is found, and even then, the chance of it being patched will decrease overtime as v2 gains maturity.

---

Hopefully this helps answer your question! Let me know if it doesn't make sense or if you need further assistance.

**Comment by Meghadi** [comment]
Thanks for the reply. 
Below is the code to set default value.
{
      useDocumentTypes: true,
      throughput: { read: 5, write: 5 },
      expires: {
        ttl: 1604133037,
        default: true,
        attribute: 'ttl',
        returnExpiredItems: false,
      }
  }
On save, I am setting the value like below,
insertField.ttl = 900

But I can get below error,
TypeError: v.getTime is not a function

**Comment by Meghadi** [comment]
To solve the below error,
TypeError: v.getTime is not a function

we need to pass input of _Date_ type to set **ttl** value ie
`insertField.ttl = new Date(new Date().getTime() + 30 * 60000))`

//Schema
obj[expires.attribute] = {
            'type': Number,
            'default': expires.defaultExpires || defaultExpires,
            'set'(v) {
                return Math.floor(v.getTime() / 1000);
            },
            'get'(v) {
                return new Date(v * 1000);
            }
        };

but in the schema we define type for **ttl** as _Number_
//Schema
 expires?: number | { ttl: number, attribute: string, returnExpiredItems: boolean };

Can we set value of _Number_ type to ttl?

**Comment by fishcharlie** [comment]
@Meghadi This is possible in v2. In v2 `ttl` is a Date (which is a custom property). But all custom properties in v2 can be stored as their underlying value. In the case of Date, that is Number. So in v2 if you have type of Date you can store it as a Number of Date. However, all the values you receive back will be type Date. As I said above, it's unlikely v1 will be updated any further, so I'd highly recommend upgrading to v2.
