### ISSUE TITLE
how to set dynamoose instance from existing dynamodb client?

### ISSUE THREAD

**Issue by bfpgresearcher** [dynamoose/dynamoose#888]
I have an existing dynamo db client and would like to create a dynamoose instance from it, is this possible and if so how do I do it?  In [the docs](https://dynamoosejs.com/getting_started/Configure) examples it looks like they create new aws instances from scratch

**Comment by fishcharlie** [comment]
@bfpgresearcher Oh yeah. Same thing. Just pass your existing DynamoDB client into `dynamoose.aws.ddb.set` and it'll work just fine. https://dynamoosejs.com/guide/Dynamoose#dynamooseawsddbsetddb

The reason I created a new one is because it's the easiest way to visualize it and understand it in my opinion. But works with existing clients as well. Totally the same thing.

**Comment by MickL** [comment]
Doesnt it make sense to exclude AWS from Dynamoose and force the user to put in an aws instance?

```
npm install --save dynamoose aws-sdk

import * as AWS from 'aws-sdk';
import * as dynamoose from 'dynamoose';

AWS.config.update(...);
dynamoose.init(AWS);
```

This would save performance because I dont have two different AWS instances in my project and remove the dependency from another project.

**Comment by fishcharlie** [comment]
@MickL Please explain the performance impact of this. I don't think there is one. Providing example projects of both the current behavior and your example and stats on the performance impact of each would be great.
