### ISSUE TITLE
How to create fully typed model?

### ISSUE THREAD

**Issue by pfulop** [dynamoose/dynamoose#889]
### Summary:
Currently, when creating a new model the model type is simply Document. I believed the same approach can be taken as with mongoose and just supply interface when creating new model.

```
export default mongoose.model<IUser>('User', UserSchema);
```

But with dynamoose doing so will result in an error:

> Type 'Stat' does not satisfy the constraint 'Document'.

With mongoose, it is easy to simply have your interface extend mongoose's Document interface, however, I can't seem to find a way to access Document interface in dynamoose as it seems to not be exported.

What is the recommended route to create fully typed Models?

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this question has not already been raised before
- [x] I have searched the internet and Stack Overflow to ensure this question hasn't been raised or answered before
- [ ] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
@pfulop What do you mean by "fully typed model"? Where document properties must conform to the model? For example:

```js
const schema = new dynamoose.Schema({
    "id": String,
    "name": String
});
const User = dynamoose.model("User", schema);

const user = new User({
    "id": 1,
    "age": 18 // This would throw a TypeScript Type Error since `age` does not exist in the Schema so therefore this document doesn't conform to User
});
```

Is that what you mean by "fully typed model"? Or something else?

**Comment by pfulop** [comment]
@fishcharlie Yes that's what I mean. But currently, the types for User are:

`const User: Document & Model<Document> & ModelDocumentConstructor<Document>`

Which translates to

`const User: new (object: {
    [key: string]: any;
}) => Document`

Which means any kind of key will satisfy the constrains.

**Comment by fishcharlie** [comment]
@pfulop Yes. That would be **amazing**. I'd love that feature. It'd be great if it could generate a dynamic interface (or something, not sure if that term is correct) based on the Schema, and have documents conform to it.

Sadly at this point, I'm unsure how to achieve that in TypeScript. I'm still pretty new to TypeScript, so really not sure how to achieve that with my current knowledge.

TypeScript Support/Typings is also in beta for Dynamoose, so it's functionality is limited at this stage.

If you want to take a shot at making a pull request to implement this, that would be great! Otherwise, it's on my radar and something I think would be super cool, but not something that is likely to be done anytime soon without support from the community.

**Comment by pfulop** [comment]
@fishcharlie I will give it a try.

**Comment by fishcharlie** [comment]
@pfulop Let me know if you have any questions or if I can assist at all. My knowledge about TypeScript is limited, but my knowledge of the Dynamoose codebase is basically complete since I wrote almost all of v2.
