### ISSUE TITLE
[FEATURE] Add linter

### ISSUE THREAD

**Issue by MickL** [dynamoose/dynamoose#896]
This project may use a linter like eslint or tslint and maybe a code formatter. Also the Gitlab CI pipeline should check for code style.

This issue is meant for discussion and keep progress.

**Comment by MickL** [comment]
Personally i hate Prettier just because it is not configurable. It is opinionated and I dont like a lot of how it styles.

I prefer to use tslint or eslint instead which are both configurable and do archive 90% what prettier does. Currently Angular sticks to tslint even tho it is deprecated because eslint is just not there where tslint is. They also do provide pretty good rules and styles for TypeScript.

I would suggest to:

- use tslint
- copy the Angular tslint rules (and remove what is Angular specific)
- Stick to the [Angular Styleguide](https://angular.io/guide/styleguide) (except what is Angular specific)

**Comment by pfulop** [comment]
I can also take this one since I would love my PR to be linted instead of me going over the formatting manually.

Since tslint is deprecated I can use eslint for this and AFAIK there are @typescript-eslint/parser and @typescript-eslint/eslint-plugin that should achieve what tslint did (I have a project where I went through the migration process).

**Comment by MickL** [comment]
Yes there are plugins but I recently switched vom eslint back to tslint. I totally understand why Angular sticks to it and would not recommend using eslint for ts right now.

**Comment by fishcharlie** [comment]
TSLint has been deprecated in favor of ESLint (https://www.npmjs.com/package/tslint). I will not be merging any pull requests that migrate to using TSLint.

**Comment by MickL** [comment]
eslint TypeScript support is not feature complete. tslint is stable and well tested over the years. Here is a roadmap for typescript-eslint: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md

Anyway I dont mind if we go for eslint

**Comment by fishcharlie** [comment]
@MickL Honestly, I've never heard someone argue for using a deprecated package or API before. That is a first for me. Especially when we are already using the replacement or recommended alternative. Seems strange to be arguing to take a step back...

I am kinda against adding Prettier to the project. It's very opinionated and I tend to disagree with the decisions it makes.

Also, please keep in mind. ESLint already exists in the project. Running `npm run lint` will run ESLint, and it gets run as part of the CI process. So I'm not really sure what the purpose of this issue is.
