### ISSUE TITLE
[BUG] From v1.11.1 to v2.1.3 to 2.2.0: scan + filter + attributes + all

### ISSUE THREAD

**Issue by matteobattista** [dynamoose/dynamoose#902]
Hi, with the new v2 my old scan no longer works ...

### Summary:

```
    // Query attributes
    const attributes = ['website', 'namespace', 'status', 'title', 'img']
    // Query filter
    // const filterOld = { ...status && { status }, ...website && { website }}
    const filter = { ...status && { "status": { eq: status } }, ...website && { "website": { eq: website } }}
    // Query scan
    const games = await gamesModel
      .scan(filter)
      .attributes(attributes)
      .all(100, 0)
      .exec()
```

The error message I recive is:
```
"Can not use both expression and non-expression parameters in the same request: Non-expression parameters: {AttributesToGet} Expression parameters: {FilterExpression}"
```

### Note
Without filter (e.g. `const filter = {}`) all works great...

What's wrong?
Thank's 

### *** Update ***
After update to 2.2.0... I have new error message:
`"Invalid ProjectionExpression: Attribute name is a reserved keyword; reserved keyword: status"`
By removing the "status" field from the attributes, everything works but it is not possible...

**Comment by fishcharlie** [comment]
@matteobattista The problem here (**I think**) is that `status` is a reserved word in DynamoDB (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ReservedWords.html). And currently we are just passing it into the `ProjectionExpression`. The solution here is to add it to `ExpressionAttributeNames` and use the key from that in the `ProjectionExpression`.

Thanks for the report! I'll get around to this as soon as I can, but feel free to create a pull request for this in the meantime if you'd like.

**Comment by matteobattista** [comment]
Hi @fishcharlie, the problem (I think) was clear ...my report wanted to be more of a warning because I think this  will be a common mistake to all those who will pass from v1 to v2 ... "status" is a reserved key but also a widely used field name ... for now I am forced to go back to v1.
If I can I will do a pull requerst
Thank you
Best regards
