### ISSUE TITLE
[BUG] Type Array does not save first item

### ISSUE THREAD

**Issue by MickL** [dynamoose/dynamoose#935]
When saving an attribute of type "Array" the first item is missing:

```
const catSchema = new Schema({
            id: String,
            names: Array,
        });

        const catModel = dynamoose.model('Cat', catSchema);

        await catModel.create({
            id: '123',
            names: [
                'a',
                'b',
                'c'
            ],
        });
```

```
aws:dynamodb:putItem:request - {
    "Item": {
        "id": {
            "S": "123"
        },
        "names": {
            "L": [
                {
                    "S": "b"
                },
                {
                    "S": "c"
                }
            ]
        }
    },
    "TableName": "Cat",
    "ConditionExpression": "attribute_not_exists(#__hash_key)",
    "ExpressionAttributeNames": {
        "#__hash_key": "id"
    }
}
```

**Comment by fishcharlie** [comment]
Strange. The expected result here is for it to save an empty array since no `schema` was defined on that array. Will look into it as soon as I'm able.

**Comment by MickL** [comment]
IMO this is the same problem I ran into like 5 times now in my project: Dynamoose does not save unknown stuff but also does not inform the user about it. This is very confusing and took me a couple of hours each time it to figure it out.

**Comment by fishcharlie** [comment]
@MickL Yeah, not sure how to make this better. I think the solution is to do something in the logger about this. Saving unknown stuff just eliminates the purpose of Dynamoose. The point is for strongly typed entries, not saving just any random data, but having some control over the schema.

That should probably be a wider discussion tho. The goal for this issue is just to investigate & fix why it saved 2 of the array items when it should have saved an empty array.
