### ISSUE TITLE
[BUG] Some errors can not be catched

### ISSUE THREAD

**Issue by MickL** [dynamoose/dynamoose#957]
Some errors can not be catched somehow and will be thrown no matter if I am using a try catch block / Promise.catch() or not. E.g. try creating and item that already exists within a try block and it will not be catched.

> (node:4012) UnhandledPromiseRejectionWarning: ConditionalCheckFailedException: The conditional request failed

**Comment by fishcharlie** [comment]
As mentioned in the issue template, `Not filling out ALL of the relevant fields in this issue will cause your issue to be closed`. There is no actionable steps here to be able to reproduce this at all. Therefore, it's near impossible to work on this issue or debug it.

**Comment by MickL** [comment]
To reproduce:

> E.g. try creating and item that already exists within a try block and it will not be catched.

**Comment by fishcharlie** [comment]
@MickL Works for me.

```js
const dynamoose = require("dynamoose");
const AWS = require("aws-sdk");
dynamoose.aws.ddb.set(new AWS.DynamoDB({"accessKeyId": "key", "secretAccessKey": "secret", "region": "us-west-2", "endpoint": "http://localhost:8000"}));

(async () => {
	const User = dynamoose.model(`User-${Date.now()}`, {"id": String, "data": String});

	await User.create({"id": "1", "data": "Hello World!"});
	console.log(`Items 1: ${JSON.stringify(await User.scan().exec(), null, 4)}`);

	try {
		await User.create({"id": "1", "data": "Hello World!"});
	} catch (error) {
		console.error(error);
	}

	console.log("DONE!!!");
})();
```

Without the try catch, `DONE!!!` never gets printed. However, with the try catch block `DONE!!!` gets printed as expected. You can see the output from the code above below.

```
Items 1: [
    {
        "data": "Hello World!",
        "id": "1"
    }
]
ConditionalCheckFailedException: The conditional request failed
    at Request.extractError (/Users/charliefish/tmp3/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/Users/charliefish/tmp3/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/charliefish/tmp3/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/charliefish/tmp3/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/charliefish/tmp3/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/charliefish/tmp3/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/charliefish/tmp3/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/charliefish/tmp3/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/charliefish/tmp3/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/charliefish/tmp3/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ConditionalCheckFailedException',
  time: 2020-06-27T22:46:51.166Z,
  requestId: '195e3393-513b-4ea8-94d7-94e6090df282',
  statusCode: 400,
  retryable: false,
  retryDelay: 30.098230588775376
}
DONE!!!
```

**Comment by fishcharlie** [comment]
@MickL As mentioned, `Not filling out ALL of the relevant fields in this issue will cause your issue to be closed`. Need a reproducible example in order to help debug.

**Comment by aecorredor** [comment]
I can confirm the same thing happens on my end on version `1.7.2`.

**Comment by aecorredor** [comment]
So I just got it working but definitely noticed something strange:

I'm using TypeScript (`3.9.9`) and running integration tests with `ts-node`. 

When doing 

```js
try {
  return User.create({"id": "1", "data": "Hello World!"});
} catch (error) {
   console.error(error);
}
```

The error is not caught.

But, when doing 

```js
try {
  await result = User.create({"id": "1", "data": "Hello World!"});

  return result;
} catch (error) {
   console.error(error);
}
```

**Comment by fishcharlie** [comment]
@aecorredor Couple things:

First. v1 line is no longer being maintained or supported. Please upgrade to v2.

Second. Your two versions of code are COMPLETELY different and do not behave the same way. `User.create({"id": "1", "data": "Hello World!"})` returns a promise. In your first block, returning a promise won't actually wait for the promise to execute. It will return out of the function and pass control back up to the caller. Therefore, the `catch` block will never be run on an error due to that function no longer haven't control anymore.

The second block, actually waits for the promise to complete before returning. This means an error will be thrown in that block and therefore `catch` will be called.

However, I've never seen `await ___ = ____`. That syntax looks very strange to me and I'm not sure it'll work. Normally you want to do `___ = await ____`.

I'd suggest looking more into how promises and async/await works in JavaScript. Those are fundamental concepts to your code here, so it is critical you understand how they are working.

> I'm not sure if it might be related to ts-node compiling code differently

Nope. Not the case. This is the expected behavior of JavaScript. Has nothing to do with TypeScript or `ts-node`.

> when directly returning the promise vs awaiting for it. I'd be very surprised if that's it though, since it'd be pretty lame

How would it be lame? It makes perfect sense. It gives the developer control over how and where to catch their errors. If you return something you are giving up control to the caller function. It's the **exact** same concept as why code below a `return` statement doesn't get run. It would be lame if it didn't behave that way. It behaves just like every other `return` statement in JavaScript...

---

As far as I can see tho, this is **not** the same issue and not even a Dynamoose issue.
