### ISSUE TITLE
[QUESTION] Type `Array` or `Object` saving empty values into database when saveUnknown is set to false

### ISSUE THREAD

**Issue by kishore-vallabhajosyula** [dynamoose/dynamoose#969]
#### Schema
const schema = new Schema(
  {
    // Shared
    pk: {
      type    : String,
      required: true,
      hashKey : true,
    },
    sk: {
      type    : String,
      required: true,
      rangeKey: true,
    },
    status: {
      type    : String,
      required: true,
    },
    name: {
      type    : String,
      required: true,
    },     
    eventData: {
      type    : Object,
      required: true,
    }, 
    history: {
      type: Array,
      required: false,
      schema: [
        {          
          status        : {
            type        : String,
            required    : false,
          },
          eventDate : {
            type        : String,
            required     : false,
          },    
        },
      ],
    },    
  {
    timestamps: true,    
    saveUnknown: true,
  },
);

#### Model
```
// Code here
```

#### General
```
// Code here
```

### Environment:

Operating System: Windows
Operating System Version: 10
Node.js version (`node -v`): 10.15.1
NPM version: (`npm -v`): 6.4.1
Dynamoose version: 2.2.0/2.2.1

### Other:
- [ ] I have read through the Dynamoose documentation before posting this issue
- [ ] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [ ] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [ ] I have tested the code provided and am confident it doesn't work as intended
- [ ] I have filled out all fields above
- [ ] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
@kishore-vallabhajosyula This issue doesn't have enough information in order to debug. What object/document are you trying to save? What is the current and expected result? Why do you not have `schema` set for `eventData`? Also, one other thing I noticed, in your `history` schema, you need to wrap that all in a `type: Object` with the schema set to that object you are currently passing in. Take a look at the last [example here](https://dynamoosejs.com/guide/Schema#schema-object--array).

At first glance, this all looks like it's behaving exactly how it's expected. You aren't defining schema for `eventData`, and `history` schema needs to be wrapped in type Object so it knows how to handle that.

It's rare that I close issues now (since we have a system for automatically closing issues). But I will be closing this one due to the clear lack of following the guidelines: `Not filling out ALL of the relevant fields in this issue will cause your issue to be closed`.

Please ensure that you read the [contributing guidelines](https://github.com/dynamoose/dynamoose/blob/master/CONTRIBUTING.md#reporting-bugs) and ensure you fill out the entire issue template so we can debug your issue easier.
