### ISSUE TITLE
[Question] Dynamoose schema- receive any Object

### ISSUE THREAD

**Issue by halinbar** [dynamoose/dynamoose#971]
Hi,
First time here, I hope I'm not completely out of scope.

I would like to define a schema that receives in a particular field an input from type Object, but without a predefined structure.
for example, let's say the schema defines something like:

`Person: Object`

I would like to have many possible inputs for Person, such as:
`{'id': '1234567489}`

and also:
`{'name': 'John',  'phone': '555555555'}
`
and basically any object, with no limitations.

I though that defining it as :
`Person: Object`
is what I'm looking for, but it doesn't seem to work.

Is there a way to achieve what I'm looking for?

Thanks

**Comment by fishcharlie** [comment]
@halinbar Sounds like what you are looking for is the [`saveUnknown` setting](https://dynamoosejs.com/guide/Schema#new-dynamooseschemaschema-options) in the Schema options. Basically if you set that to `saveUnknown: ["Person.**"]` that will match all nested properties within `Person` and all it to be saved.

Now, in the two examples you gave, you could also do `saveUnknown: ["Person.*"]` since all properties you want to save are only 1 level deep. `*` will translate to only one level deep wildcard, and `**` is infinite levels deep of wildcard. So just based on what you said that you want to allow **ANY** object, you are looking for `**`. However, if you are confident that it's only one level deep and no further nested properties, I'd suggest `*`. But just answering your question you want `**`.

**Comment by halinbar** [comment]
Thanks so much for the quick and detailed response! 
I'm still not sure how to use it properly though.

Here's exactly what I'm doing to define the schema:
`const ActionSchema = new Schema({`
     `     ID: {
      type: String,
      hashKey: true,
     },`
     `    Person: {
    type: Object,
    required: false,
  }, `
     `  saveUnknown: ["Person.*"],`
`});`

and my input for Person is:
`{'name': 'John'}`

but in the table I only get an empty object for Person.

Am I missing something?

**Comment by fishcharlie** [comment]
@halinbar 

---

Short version. `saveUnknown` is part of the options parameter/argument (https://dynamoosejs.com/guide/Schema#new-dynamooseschemaschema-options).

---

Long version. The `new Schema` constructor takes in 2 arguments. The first is your schema object (like you have). Then the second is an optional object that defines the options.

In your case, you are putting `saveUnknown` as part of the schema object, instead of as part of the options object. The `saveUnknown` setting should be part of the options object not the schema object.

Changing your code example to the following should work:

```js
const ActionSchema = new Schema(
{
    ID: { type: String, hashKey: true, },
    Person: { type: Object, required: false, }
},
{
    saveUnknown: ["Person.*"],
}
);
```

Apologizes for the awful formatting, but I thought it was the best way to make it clear what is going on here.

**Comment by halinbar** [comment]
Awesome!
Thanks so much for the attention, it's much clearer now.
And also- it works :)
