### ISSUE TITLE
[FEATURE] Pagination Plugin

### ISSUE THREAD

**Issue by SilentHunter124** [dynamoose/dynamoose#979]
### Summary:
In the development I always come over the problem to paginate over queries. In former times when working with mongoose it was quite easy with that: https://www.npmjs.com/package/mongoose-paginate-v2

Is same thing possible here? Even by different pagination strategy?

This problem is always recurring so why not integrate it directly?

### Other:
- [X] I have read through the Dynamoose documentation before posting this issue
- [X] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this feature has not already been suggested before
- [X] I have filled out all fields above
- [X] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
@SilentHunter124 Wanna comment on #851 with this idea? Pagination is something that is kinda difficult I've found in Dynamoose. Since so much of it takes place on the client side, there aren't very many efficient ways to handle it, from my experience. Which is why I'm semi opposed to implementing it.

The ideal scenario here is for DynamoDB to add better support for pagination, and for Dynamoose to implement that.

The reason why I'm opposed to doing it ourselves, is I feel like there is a chance that right after we implement it, DynamoDB will add better support for it, making our solution obsolete. It also has a strong potential to create breaking changes if we want to migrate to their new system.

A similar thing happened with Objects and Arrays. Dynamoose implemented them by converting to JSON, then storing as a string, then parsing it on the retrieve side of things. Then DynamoDB added native support for it. Which was (and still kinda is) a HUGE pain to migrate from. If we had just held off on that, we could have implemented it the correct way.

I'd encourage you to contact AWS and give them your feedback. I don't see us implementing this natively into Dynamoose anytime soon (unless DynamoDB adds better functionality for this).

Plugin support (that isn't maintained by Dynamoose) might be possible after we add support for that. Or someone building a wrapper around Dynamoose is also possible. But it's unlikely I'll contribute much (if at all) to those projects.
